### ISSUE TITLE
[Google Play Product API] Results are Sometimes Empty When Paginating

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1169]
A customer reported they are getting results with `"organic_results_state":"Fully empty"` for some pagination requests in our Google Play Product API.

When testing in the Playground, I found that the search they shared sometimes returns results and sometimes does not.

<img width="1459" alt="Screenshot 2023-10-23 at 11 05 07 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/57aeb2b3-f273-43f5-8128-fd87dd8c5c04">
<img width="1452" alt="Screenshot 2023-10-23 at 11 04 47 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/80d58485-c175-4993-9c43-62b167d181ce">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/5859719/conversation/102910000048979?view=List) | [Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&next_page_token=CncKdQpzMCw0MTg1OTUuNDg0NTY1ODczMjIsMTIxNTE0MTkyNDMxLCJodHRwOi8vbWFya2V0LmFuZHJvaWQuY29tL2RldGFpbHM_aWQ9djI6Y29tLnBvcHVsYXJhcHAucGVyaW9kY2FsZW5kYXI6MSIsMSxmYWxzZQ&no_cache=true) | [Inspector 1](https://serpapi.com/searches/65369d69e135086681f73636/inspect) | [Inspector 2](https://serpapi.com/searches/6536b43066d81f84be93a311/inspect)

**Comment by schaferyan** [comment]
The customer followed up on this

**Comment by andypple83** [comment]
I try to reproduce this issue, here is what I'm finding:

When I searched with [default params](https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&no_cache=true), we were able to scrape the page:

![Screenshot 2024-01-22 at 17 35 21](https://github.com/serpapi/public-roadmap/assets/99160364/6be0a616-d8b9-434e-b3bf-3011a1e0e6f7)

Then I use "[next page token](https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&next_page_token=CnUKcwpxMCwxMDAxMDAwLjQ3NjgxNzI4LDEzOTUzNDc1ODc1OCwiaHR0cDovL21hcmtldC5hbmRyb2lkLmNvbS9kZXRhaWxzP2lkPXYyOmNvbS5wb3B1bGFyYXBwLnBlcmlvZGNhbGVuZGFyOjEiLDEsZmFsc2U&no_cache=true)", it works as expected

![Screenshot 2024-01-22 at 17 35 55](https://github.com/serpapi/public-roadmap/assets/99160364/99cb8f24-3e56-4cdb-b27f-82850e9a5af2)

I tried multiple next page tokens, it still works as expected too.

But when I changed some params, let's take the [previous successful searches](https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&next_page_token=CnUKcwpxMCwxMDAxMDAwLjQ3NjgxNzI4LDEzOTUzNDc1ODc1OCwiaHR0cDovL21hcmtldC5hbmRyb2lkLmNvbS9kZXRhaWxzP2lkPXYyOmNvbS5wb3B1bGFyYXBwLnBlcmlvZGNhbGVuZGFyOjEiLDEsZmFsc2U&no_cache=true):

When I change `sort_by` from `Relevant` to `Newest`, the search will be failed:

![Screenshot 2024-01-22 at 17 38 38](https://github.com/serpapi/public-roadmap/assets/99160364/b189109f-4c0f-442e-8ec0-3af741b891a7)

Because it's in different order and the `next_page_token` should be different.(Note: When I changed `sort_by` back to `Relevance`, it works)

I checked other params: `all_reviews`, `platform`, `rating`, `num`. When I changed them, the pagination results are still working.

I checked the Intercom, I'm not too sure if clients are changing `sort_by` in their script or not. I'm happy to review the script. Thanks.

cc @schaferyan do you think we should add some documents or enrich our description for parameters: `sort_by` or `next_page_token`?

**Comment by schaferyan** [comment]
Thanks @andypple83. Yes, I think it's worth adding a note to the documentation of `sort_by` that changing the value mid-pagination can have unexpected results.

I don't see anything indicating that the customer was doing that - unfortunately, the searches seem to be expired.

I will say that I tried submitting the same search with the same parameters multiple times in the [Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&next_page_token=CncKdQpzMCw0MTg1OTUuNDg0NTY1ODczMjIsMTIxNTE0MTkyNDMxLCJodHRwOi8vbWFya2V0LmFuZHJvaWQuY29tL2RldGFpbHM_aWQ9djI6Y29tLnBvcHVsYXJhcHAucGVyaW9kY2FsZW5kYXI6MSIsMSxmYWxzZQ&no_cache=true), using the example they provided (which included a `next_page_token`). It worked some of the times and at least once returned empty results.

I will follow up with the customer to check whether they changed `sort-by`.

**Comment by schaferyan** [comment]
According to the customer, they never changed the value of `sort-by`.

I've also reconfirmed that when I retry this search that includes the `next_page_token` multiple times, it sometimes works and sometimes returns empty:

https://serpapi.com/playground?engine=google_play_product&product_id=com.popularapp.periodcalendar&gl=us&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=1&next_page_token=CncKdQpzMCw0MTg1OTUuNDg0NTY1ODczMjIsMTIxNTE0MTkyNDMxLCJodHRwOi8vbWFya2V0LmFuZHJvaWQuY29tL2RldGFpbHM_aWQ9djI6Y29tLnBvcHVsYXJhcHAucGVyaW9kY2FsZW5kYXI6MSIsMSxmYWxzZQ&no_cache=true

<img width="1464" alt="Screenshot 2024-01-23 at 10 54 06 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5562e641-6768-4b65-8be6-042832641d1b">
<img width="1464" alt="Screenshot 2024-01-23 at 10 53 49 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/ad214069-d416-4ba0-8d35-4413acf95c82">

**Comment by hilmanski** [comment]
A user faced this bug as well. 

- [His inspect information: failed](https://serpapi.com/searches/65ef7107c504e98730cb4d38/inspect)
- [My inspect information: success](https://serpapi.com/searches/65f11badd5b1c5d0ccbf561f/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060653?view=List)

**Comment by andypple83** [comment]
Thanks for reporting this issue. Google returns errors for some requests. The errors are handled now. Let me know if you encounter any failed searches.
