### ISSUE TITLE
[Google Lens Image source API] Blurred thumbnail image

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1178]
A customer reported that the Google Lens Image Source API returns blurred images. I'm not sure if it's something coming from Google itself or on SerpApi implementation.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000052812?view=List) 

I found similar things happen when requesting this page: [Playground link](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=NTczOGExZTQtZmJmNC00ODY5LTkxZmQtYTY1N2ZhZjRjZDQ2) | [Inspect](https://serpapi.com/searches/653a2987ca968fb5fea61532/inspect)

See the first result:
![Screenshot 2023-10-26 at 14 30 41](https://github.com/serpapi/public-roadmap/assets/4522467/c06b5e97-91d5-4105-ad2d-f49f1b04728b)

**Comment by KazChe** [comment]
>Images found on  "gstatic.com/" are the cached version of the image stored on Google's servers to speed up the delivery.

See [Google Search Help](https://support.google.com/websearch/thread/215432303?hl=en&msgid=215432928) 
Not sure about the resolution, but from what I see in the thread above "it's a waiting game for it to be gone"?

**Comment by martin-serpapi** [comment]
This seems to be caused by the SafeSearch option:

[Google Lens search](https://lens.google.com/search?ep=gisbubu&hl=en&re=df&p=AbrfA8otJovX5TMbRNekOM6lXb3tysNYV1e6tru9mK6Viknjr02NOf815W2Diurr-hpPOUslZV8I2t1zAxIx_7KAgMyy6rhJ0qBF3IlLeI1g-yqn8xRjw8XzsKPdxZv8ohEW-BPSl5CPzy-dLW7q9rzD2i48Ht6161nzKDGgV_SqIvD3SmhSDDSFBKgqdhLO5gE7l7WesTtXgYBR7BfX2seibHj4YPvaJkT2Ol2MKMqRMFvPBcL-p2GVMH4n5678RoMUdj1wGJh_HVR36cnxFt_3dQiqQSKignyeWRsmAvgBRjMQNRbOor_D5q_dNHi2lm2pGlrZ2leyCipvjIn-bh0hHHdSTveq0jkl8iD718jnOCrSyRVpp_CN&sa=X&ved=0ahUKEwicntHOnqCCAxXozwIHHaoGDWsQkYoICAE#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsIkNpUmtNemRsTkdJMVppMWpNR0prTFRReFpXTXRZakk0TlMweVpEbGtPVGhoWVRZd09EVVNIM04zTmxaek0xQk1lbmswVWpSR00zQkVNblk0WVdOMVpWbDJjRnAxUW1jPSIsbnVsbCxudWxsLFtbbnVsbCxudWxsLG51bGwsbnVsbCw4MF0sW11dLG51bGwsbnVsbCxudWxsLFtudWxsLG51bGwsW11dXQ==)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/93e37089-3e23-4491-988e-67a065a67641)

When I disable the SafeSearch, there are no blurred images in the response:

[Google Lens search](https://lens.google.com/search?ep=gisbubu&hl=en&re=df&p=AbrfA8otJovX5TMbRNekOM6lXb3tysNYV1e6tru9mK6Viknjr02NOf815W2Diurr-hpPOUslZV8I2t1zAxIx_7KAgMyy6rhJ0qBF3IlLeI1g-yqn8xRjw8XzsKPdxZv8ohEW-BPSl5CPzy-dLW7q9rzD2i48Ht6161nzKDGgV_SqIvD3SmhSDDSFBKgqdhLO5gE7l7WesTtXgYBR7BfX2seibHj4YPvaJkT2Ol2MKMqRMFvPBcL-p2GVMH4n5678RoMUdj1wGJh_HVR36cnxFt_3dQiqQSKignyeWRsmAvgBRjMQNRbOor_D5q_dNHi2lm2pGlrZ2leyCipvjIn-bh0hHHdSTveq0jkl8iD718jnOCrSyRVpp_CN&sa=X&ved=0ahUKEwicntHOnqCCAxXozwIHHaoGDWsQkYoICAE#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsIkNpUTNNR1EyWldaaE5pMHhPREJsTFRSa09EY3RZVFU1TXkxaE1XWTVNamd5WkRFNVpESVNIMEUwY21WYWNpMVdXRk5SVkRSR00zQkVNblk0WVdOMlQxZzNPV0YxUW1jPSIsbnVsbCxudWxsLFtbbnVsbCxudWxsLG51bGwsbnVsbCw4MF0sW11dLG51bGwsbnVsbCxudWxsLFtudWxsLG51bGwsW11dXQ==)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/b908d46a-4054-47bf-b712-81e049323187)
