### ISSUE TITLE
[Google Play Product] Empty results with `all_reviews=true` and `sort_by=3` (Rating).

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1203]
We can not scrape content with `all_reviews: true`
![Screenshot 2023-11-14 at 17 14 31](https://github.com/serpapi/public-roadmap/assets/99160364/5b053a0d-8fe6-4ba8-a9bd-635af3a49669)

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=KjWNBwAAQBAJ&gl=us&store=books&all_reviews=true&platform=tablet&sort_by=3&no_cache=true) | [Inspect](https://serpapi.com/searches/655348afa4bb38f74432f603/inspect)

**Comment by aciddjus** [comment]
The issue seems to appear only when `sort_by` is set to `3` (Rating).

Here is the search when `sort_by` is not set to `3`:

<img width="1903" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/0bf5391d-6de3-4dba-87b3-810cb71ad356">


[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=KjWNBwAAQBAJ&gl=us&store=books&all_reviews=true&platform=tablet&sort_by=1&no_cache=true)
[Inspect](https://serpapi.com/searches/65577c86a5ad6d6bba74b0a8/inspect)

**Comment by andypple83** [comment]
For `google_play_product` engine, we don't support `sort_by: Rating` for `store: Books`

![Screenshot 2024-02-23 at 13 55 51](https://github.com/serpapi/public-roadmap/assets/99160364/2471c3a1-fc13-49f2-8b8b-16b509eb7cf0)

`sort_by: Rating` is still available for other for `store: Apps, Games...`

![Screenshot 2024-02-23 at 13 55 30](https://github.com/serpapi/public-roadmap/assets/99160364/e672a6d0-489c-4bb9-90a4-fcb8dbfc1cc1)
