### ISSUE TITLE
[Google Shopping API] Price per month instead of total price returned for some products

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1265]
Hi team a customer reported that a price per month is returned for some products, instead of the total price. I was able to reproduce the issue:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/fc39cfbb-a5fe-4c7d-878b-b43926741244)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=RTX+4060+Ti&gl=br&hl=pt) | [Inspect](https://serpapi.com/searches/656f4e59b5961e91a0996202/inspect)

The actual Google Shopping engine displays the total price for the same product:

https://www.google.com/search?tbm=shop&hl=pt&gl=br&q=RTX+4060+Ti

<img width="1261" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/07b32079-df46-4f4c-a1bb-41990ac56079">
 
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054783?view=List)

**Comment by schaferyan** [comment]
The customer added the note that they are only seeing this issue when setting `gl=br`.

**Comment by aliayar** [comment]
I don't think that this is a bug but a feature of Google Shopping API.

Big retailers in developing countries mostly show their prices in monthly installments instead of full price so that their products is affordable by masses. At least, this is my experience from Turkey. Brazil might be similar in that regard and that might be the reason why Google Shopping shows prices for monthly installments instead of full price.

**Comment by hartator** [comment]
Let's close this as a `wontfix` as it's just actual prices indeed.
