### ISSUE TITLE
On Google Jobs Listing API, 'Apply options' are not extracted anymore

### ISSUE THREAD

**Issue by bhaskar2choudhary** [serpapi/public-roadmap#1303]
Since 13th December, 2023 we are not receiving "Apply Options" for jobs when we use Google Jobs Listing API.

**Steps to reproduce -**

1. Get a job id for any job from Google Jobs API - https://serpapi.com/playground?engine=google_jobs&q=data+analyst+india. Sample job id - eyJmYyI6IkVvd0NDc3dCUVV4UGJuQlpWMmhQVFdWR2QxQkhTMUk1VVZkNVVtOUlSVEZ1VGpOb1kxQjFTSGhGV2pkSGJFcDVVV3BFYjNwS1lWTTVjRmhMVTA4M2FVczNkblJXYUZNNVRVUklaREZEZGtwNGMwdGFWRXB3Y21WU1pWQTRVRGxGYlhwa1MxZEhlVjkxVlVkbE9XUlJaV1J2TlVzMVEweFdjVmRzZEZsTFZHRllWWGxFYWpOTVdURlpkR2wyYjFCdVMwOU1VMUIyV0hKUlgwY3Rka3BaY1cxRVdHVmxMWGw1UjJGc1ZsOUdNRWRHWm14aVRraGtjbGhzWkVsS1gzTnlZbEZVTXpFMllqazJSemR5U0ZGMmMydHFFaGRFYWt0QldtTmxNa1ZmUjJod2RGRlFjR1JQUmpCQmJ4b2lRVXAzYXkwNFpXRmlWMlJxTUdreWNGZG9OWFJDTm5NMWQxOU5VMlZ6VkU1Slp3IiwiZmN2IjoiMyIsImZjX2lkIjoiZmNfMyIsImFwcGx5X2xpbmsiOnsidGl0bGUiOiJBcHBseSBkaXJlY3RseSBvbiBTXHUwMDI2UCBHbG9iYWwiLCJsaW5rIjoiaHR0cHM6Ly9jYXJlZXJzLnNwZ2xvYmFsLmNvbS9qb2JzLzI5NDQ3MD9sYW5nPWVuLXVzXHUwMDI2dXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ==
2. As seen in UI, there are multiple Apply options but when you can Google jobs API, it doesn't return any option. Earlier it used to. - https://serpapi.com/playground?engine=google_jobs_listing&q=eyJmYyI6IkVvd0NDc3dCUVV4UGJuQlpWMmhQVFdWR2QxQkhTMUk1VVZkNVVtOUlSVEZ1VGpOb1kxQjFTSGhGV2pkSGJFcDVVV3BFYjNwS1lWTTVjRmhMVTA4M2FVczNkblJXYUZNNVRVUklaREZEZGtwNGMwdGFWRXB3Y21WU1pWQTRVRGxGYlhwa1MxZEhlVjkxVlVkbE9XUlJaV1J2TlVzMVEweFdjVmRzZEZsTFZHRllWWGxFYWpOTVdURlpkR2wyYjFCdVMwOU1VMUIyV0hKUlgwY3Rka3BaY1cxRVdHVmxMWGw1UjJGc1ZsOUdNRWRHWm14aVRraGtjbGhzWkVsS1gzTnlZbEZVTXpFMllqazJSemR5U0ZGMmMydHFFaGRFYWt0QldtTmxNa1ZmUjJod2RGRlFjR1JQUmpCQmJ4b2lRVXAzYXkwNFpXRmlWMlJxTUdreWNGZG9OWFJDTm5NMWQxOU5VMlZ6VkU1Slp3IiwiZmN2IjoiMyIsImZjX2lkIjoiZmNfMyIsImFwcGx5X2xpbmsiOnsidGl0bGUiOiJBcHBseSBkaXJlY3RseSBvbiBTXHUwMDI2UCBHbG9iYWwiLCJsaW5rIjoiaHR0cHM6Ly9jYXJlZXJzLnNwZ2xvYmFsLmNvbS9qb2JzLzI5NDQ3MD9sYW5nPWVuLXVzXHUwMDI2dXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D

**Comment by jacob-restart** [comment]
Same here!

**Comment by schaferyan** [comment]
Hi, @bhaskar2choudhary thanks for opening this issue. This is a known bug, we have documented it here:

https://github.com/serpapi/public-roadmap/issues/1259

We're working toward a solution and will update you when it's implemented. Thank you so much for your patience in the meantime.

**Comment by schaferyan** [comment]
@bhaskar2choudhary and @jacob-restart I wanted to let you know our engineers have implemented a fix. The Google Jobs Listing API now works as expected. You can see an example here:

https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJDYWZmZSBNYWNzIEJhcmlzdGEiLCJodGlkb2NpZCI6Ik5wTmJiSmw2aVJTUXJRYk9BQUFBQUE9PSIsImZjIjoiRW93Q0Nzd0JRVXhQYm5CWlYwaFVNVEEzTVhwUmVUSkJORE5yVlZwM2VqRkJTelZ6WmtaTVVtUkVSSGQzVDJaMlVrMXJMVFJQVEVJeVJUQTJXV2w2Y2pSbVRIZEVNM0pUZWpCS1YyaHZMWHB5ZW10V1MyeFRNRTUzTlVKNVlVbG9VVXBKVm1sMVZrazViWFJhY1doRmNtaENRVmgwYVV0SloydzFUak00WDFZME1sSjNaWEZtVFd0V2JUZzFiemRPVkZwa05UTnBiMlJYWm5aUFZsSTJVSEpYZUc1aldUTTVTWFpRU1UxNFJsSnVjRFpGY1hCQ01ITnVZbmRrYm5WWVQwSmFRakl0Y0dKRVEyVlJOamhxWVc1QkVoZHJhV1ZFV21NeVIwTmpiWHB3ZEZGUWJqZGhNSE5CWnhvaVFVcDNheTA0WTJwcmRWOXFNVkJLVjJGTWNYRm9NRk5GVkhwWFVrTnRNRU5yWnciLCJmY3YiOiIzIiwiZmNfaWQiOiJmY18xIiwiYXBwbHlfbGluayI6eyJ0aXRsZSI6Ii5uRmcyZWJ7Zm9udC13ZWlnaHQ6NTAwfS5CaTZEZGN7Zm9udC13ZWlnaHQ6NTAwfUFwcGx5IG9uIENhcmVlcnMgQXQgQXBwbGUiLCJsaW5rIjoiaHR0cHM6Ly9qb2JzLmFwcGxlLmNvbS9lbi11cy9kZXRhaWxzLzIwMDUwNTM4MC9jYWZmZS1tYWNzLWJhcmlzdGE%2FdXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D

Note that any job_ids you may already have from querying our Google Jobs API may be incomplete, we recommend using the Google Jobs API again to extract these now that the fix is in place.

Thank you so much for your patience during this process.

**Comment by bhaskar2choudhary** [comment]
Thank you so much @schaferyan !
