### ISSUE TITLE
html_results = search.get_html() Only get parsed JSON file, no the raw html

### ISSUE THREAD

**Issue by godzkh** [serpapi/public-roadmap#1331]
I tried to access raw html to add some debug parse, however,  search.get_html() only return the json result.

**Comment by schaferyan** [comment]
Hi @godzkh, thank you for opening this issue. 

I've confirmed that the `get_html()` function when using our `google-search-results-python` library seems to return a JSON response instead of the expected HTML.

You can get the raw HTML either by adding `"output":"html"` to the parameters in your request, or from the URL provided in the `raw_html_file` key in the JSON response. I hope this helps - feel free to reach out to us using the chat interface or email us at **support@serpapi.com** on our website or email for further assistance.

**Comment by godzkh** [comment]
I see, then I can not do tailing html analysis just using one api call to serpapi. Please add an include_raw_html param in the future. Thanks.

**Comment by schaferyan** [comment]
@godzkh I'm sorry about that. I'm not sure why the `get_html()` method isn't returning HTML. I'm opening an issue in our Python library repository to address this.

However, as I mentioned above, we do have a parameter supporting this. If you add the `output` parameter and set its value to `html`, you will receive the response as raw HTML. Let me know if this solves the problem for you.

**Comment by schaferyan** [comment]
@godzkh I've opened an issue in the Python library repo for this:

https://github.com/serpapi/google-search-results-python/issues/66

Feel free to add your comments there if needed.

I'm closing this issue, as this appears only to affect the Python library.

You can reach out to us via our chat interface or email us at **support@serpapi.com** at any time if you need any further assistance.

**Comment by godzkh** [comment]
Thanks a lot for the help, looking forward to the fix.
