### ISSUE TITLE
[Google Flight API] No Explanation of "city ID"

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1344]
A user recently asked how to find the city ID for use with our Google Flight API.

Our documentation doesn't include any information about how to get a city ID:

<img width="895" alt="Screenshot 2024-01-10 at 5 09 52 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/39726a30-a278-4d60-82e6-cd6153f9eb92">

In the PR to add the Google Flights API, it is noted that the city ID would be difficult for our users to find without making a new engine.

It seems to correspond with the Freebase ID of cities, which can be retrieved via Wikipedia, however, I haven't verified consistency on this. I assume it can also be gotten from Google since they are using it internally, but I haven't found an easy way to do this that can be shared with our customers.

I think mentioning it without explaining how to get it creates more confusion. We should either add a list of city IDs, or an engine to generate the city ID if we want to support this feature. 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000056843?view=List)

**Comment by marm123** [comment]
Until we have an engine or a way to easily extract the `city_id` parameter, we can advise customers to use the wikidata page to find the `id`. Here are the steps to search for the `city_id`:

1. Search "Paris (or any other city) Freebase id" via Google:
<img width="970" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9351de91-8395-481e-843c-34f4051f99d6">

2. Open the Wiki page and search for `/m/`:
<img width="1002" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/cb542a9b-b4e4-4ff9-8e2a-247172244dbc">

3. Copy the value and use it with our Google Flights API:
<img width="1437" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/1fc7b4d3-8fa6-4998-9950-f7c6a51aa845">

I know it's not ideal, and there is a lot of manual work with that solution, but I think it's at least some way for our customers to get the `city_id` if they need it.

**Comment by marm123** [comment]
I've tried a couple of examples from the Wiki for the Freebase ids, and it seems that this can be a valid workaround, as you mentioned @schaferyan. Until we have a proper way to extract the `city_id` parameters, we can guide customers to search for these ids.

Additionally, the `city_id` is basically `kgmid` parameter from the Google's `knowledge_graph`, so there is another way to get this (as soon as we fix the issue here https://github.com/serpapi/public-roadmap/issues/772)

[Paris wiki](https://www.wikidata.org/wiki/Q90) | [Paris Playground](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F05qtj&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18) | [Paris `kgmid` search](https://www.google.com/search?kgmid=/m/05qtj)
[Berlin wiki ](https://www.wikidata.org/wiki/Q64)| [Berlin Playground](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F0156q&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18) | [Berlin `kgmid` search](https://www.google.com/search?kgmid=/m/0156q)
[Madrid wiki](https://www.wikidata.org/wiki/Q2807) | [Madrid Playground](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F056_y&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18) | [Madrid `kgmid` search](https://www.google.com/search?kgmid=/m/056_y)
[Tokyo wiki ](https://www.wikidata.org/wiki/Q1490)| [Tokyo Playground](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F07dfk&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18) | [Tokyo `kgmid` search](https://www.google.com/search?kgmid=/m/07dfk)
[New York wiki](https://www.wikidata.org/wiki/Q60) | [New York Playground ](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F02_286&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18)| [New York `kgmid` search](https://www.google.com/search?kgmid=/m/02_286)
[Cairo wiki](https://www.wikidata.org/wiki/Q85) | [Cairo Playground](https://serpapi.com/playground?engine=google_flights&departure_id=%2Fm%2F01w2v&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-12&return_date=2024-01-18) | [Cairo `kgmid` search](https://www.google.com/search?kgmid=/m/01w2v)
