### ISSUE TITLE
[Google Trends API] Allow searches with combined length of keywords greater than 100

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1395]
We recently implemented a change in https://github.com/serpapi/SerpApi/pull/4473 that doesn't allow searches longer than 100 characters in Google Trends API, which is valid if we use one keyword. However, Google Trends allows searches with multiple keywords where the combined length of the query is greater than 100. Here is a search query using a total of 170 characters (including 4 commas):

https://trends.google.com/trends/explore?date=now%201-d&geo=PL&q=Pneumonoultramicroscopicsilicovolcanoconiosis,Pseudopseudohypoparathyroidism,Floccinaucinihilipilification,Antidisestablishmentarianism,Supercalifragilisticexpialidocious&hl=en
<img width="1668" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/c11287f1-9943-4bf7-b2f0-e6ee272cf68a">

The same query is not accessible via our API:
<img width="1677" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/59033994-cff2-461f-a7aa-61955647eeaa">

Maybe we can implement a solution that would identify if it's a single keyword, or multiple keywords separated by a comma, where each of them doesn't exceed 100 characters, but all of them combined could.

[Playground](https://serpapi.com/playground?engine=google_trends&q=Pneumonoultramicroscopicsilicovolcanoconiosis%2CPseudopseudohypoparathyroidism%2CFloccinaucinihilipilification%2CAntidisestablishmentarianism%2CSupercalifragilisticexpialidocious) | [Google Trends search](https://trends.google.com/trends/explore?date=now%201-d&geo=PL&q=Pneumonoultramicroscopicsilicovolcanoconiosis,Pseudopseudohypoparathyroidism,Floccinaucinihilipilification,Antidisestablishmentarianism,Supercalifragilisticexpialidocious&hl=en)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058492?view=List)

**Comment by hartator** [comment]
Let's keep that 100 chars limit for now as we've been struggling to keep that API up and the current Intercom request is not coming for a current customer.

**Comment by ilyazub** [comment]
Our [important customer](https://app.intercom.com/a/apps/_/users/5e6ac4aa78ec1a47e865d674) couldn't make about 1,000 searches daily because of the incorrect validation on our side. Although, they didn't say anything about that via Intercom.

![image](https://github.com/serpapi/public-roadmap/assets/282605/82883855-6eff-4fbd-94dc-c252a4ebb758)

[Playground](https://serpapi.com/playground?engine=google_trends&q=%C3%89ruption+volcanique+Islande%2CMeta+Intelligence+artificielle%2CBernard+Laporte%2CProfit+B%C3%A9n%C3%A9fice+par+action%2COdell+Beckham+Jr.)

![image](https://github.com/serpapi/public-roadmap/assets/282605/a3d6ad3b-aeb3-4935-a1b1-f861a984f060)

**Comment by tanys123** [comment]
We have released a fix. It's now accept total query length greater than 100, but each query must be less than or equal to 100.

<img width="1457" alt="Screenshot 2024-02-26 at 4 30 19 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/6ef9ff38-7a31-4303-bf71-ab85adac8c5e">
