### ISSUE TITLE
[Google Flights API] Invalid departure_token

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1413]
An invalid departure_token shows when performing a search with departure_token.

Example search: 
[Playground: simple flight search](https://serpapi.com/playground?engine=google_flights&departure_id=UPG&arrival_id=KUL&gl=us&hl=en&currency=USD&outbound_date=2024-02-16&return_date=2024-02-22)

[Inspect](https://serpapi.com/searches/65cdaaaa49ecdb3d309396f3/inspect)

[Playground: flights with departure_token](https://serpapi.com/playground?engine=google_flights&departure_id=UPG&arrival_id=KUL&gl=us&hl=en&currency=USD&outbound_date=2024-02-16&return_date=2024-02-22&departure_token=WyJDalJJVEZsMU5Wa3RRa3hVYkVGQlFuRnNibWRDUnkwdExTMHRMUzB0TFMxMmRIcHBOa0ZCUVVGQlIxaE9jWEZ6UlRKeldtdEJFZ3RSUnpNMU5YeFJXak15TWhvTENMYTlBUkFDR2dOVlUwUTRISEMydlFFPSIsW1siVVBHIiwiMjAyNC0wMi0xNiIsIlNVQiIsbnVsbCwiUUciLCIzNTUiXSxbIlNVQiIsIjIwMjQtMDItMTYiLCJLVUwiLG51bGwsIlFaIiwiMzIyIl1dXQ)

I Can't share the inspect number since it shows an error.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059156?view=List)

**Comment by marm123** [comment]
The issue here is that the `departure_token` is actually invalid. The `==` at the end of the token was not copied:
<img width="1675" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/269fbed2-41af-4848-b44d-894e49dbaffd">

<img width="177" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/c94b1f1f-05f5-49de-a1e5-0f7c775ce696">

If you add the == at the end, the search works:

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=UPG&arrival_id=KUL&gl=us&hl=en&currency=USD&outbound_date=2024-02-16&return_date=2024-02-22&departure_token=WyJDalJJVEZsMU5Wa3RRa3hVYkVGQlFuRnNibWRDUnkwdExTMHRMUzB0TFMxMmRIcHBOa0ZCUVVGQlIxaE9jWEZ6UlRKeldtdEJFZ3RSUnpNMU5YeFJXak15TWhvTENMYTlBUkFDR2dOVlUwUTRISEMydlFFPSIsW1siVVBHIiwiMjAyNC0wMi0xNiIsIlNVQiIsbnVsbCwiUUciLCIzNTUiXSxbIlNVQiIsIjIwMjQtMDItMTYiLCJLVUwiLG51bGwsIlFaIiwiMzIyIl1dXQ%3D%3D)

**Comment by hilmanski** [comment]
I apologize for the confusion. Thank you very much Bartek!
