### ISSUE TITLE
[Google Product API] `typical_prices` missing in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1454]
A user reported that `typical_prices` is missing in the response from our Google Product API. I was able to reproduce it in the Playground.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/ca1ca0bb-1eb2-44e2-9125-a7215b77526e)

[Playground](https://serpapi.com/playground?engine=google_product&product_id=17732503408543394878&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/65e6b90edefa1378896d8bfa/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060510?view=List)

**Comment by Freaky** [comment]
This should now be resolved.

In addition to `typical_prices` being scraped again, `product_id` is now presented as a `String` in order to ensure interoperability with languages lacking 64-bit integers and make it consistent with the same field in the Google Shopping API:

![before-json](https://github.com/serpapi/public-roadmap/assets/58758/50524e6e-1d2b-4a1e-ad1a-9af2f0f75329)

Note the incorrect end digits - the field is correctly serialized but cannot be processed correctly by JavaScript.

![after-json](https://github.com/serpapi/public-roadmap/assets/58758/64ae94f7-c7b0-4485-b6a6-1eb41248ab64)

Low and high are also scraped if they're present.

The documented field structure has also been corrected, with the [Google Product API](https://serpapi.com/google-product-api) and [Google Product Page](https://serpapi.com/product-page) now showing the correct field structure and types.
