### ISSUE TITLE
[Google Local Search API] `reviews` Parsed Incorrectly

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1466]
A high-volume customer reported we are not correctly parsing the number of `reviews` in some cases.

In the example the customer shared, the `reviews_original` value seems to be correct, but we are not correctly parsing it into a number format.

From what I can see, this seems to be a problem for results with > 1000 reviews when `hl=es`. It may affect large numbers in other languages as well, but it doesn't currently seem to be a problem when `hl=en`.

<img width="1087" alt="Screenshot 2024-03-11 at 2 54 14 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/939a2f75-3155-40c3-8093-c294f3bdee27">

[Inspector](https://serpapi.com/searches/65ef794f797ac61d1ceeefae/inspect) | [Playground](https://serpapi.com/playground?engine=google_local&q=Makeup+Barcelona%2C+Catalonia%2C+Spain&location=Barcelona%2C+Catalonia%2C+Spain&google_domain=google.es&gl=es&hl=es&device=desktop) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060928?view=List)

**Comment by kagermanov27** [comment]
This issue is resolved now. The Spanish abbreviation for thousand `mil` is supported.

Before:
![image](https://github.com/serpapi/public-roadmap/assets/73674035/8ad49d63-cb32-4086-a116-7aba3725f6ad)

After:
<img width="1148" alt="Pasted Graphic 2 copy" src="https://github.com/serpapi/public-roadmap/assets/73674035/b6495dbc-7c15-4084-b25c-3cb13b35ed1c">
