### ISSUE TITLE
[Google Shopping API] base64 for thumbnail image

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1472]
This is a question.

A user asked if they could receive a base64 instead of the image URL on the thumbnail in the shopping_results response from Google Shopping API.

On the API documentation, we mentioned that the thumbnail can be a base64 or an image URL
![CleanShot 2024-03-13 at 07 15 33](https://github.com/serpapi/public-roadmap/assets/4522467/12e4bd27-b590-4d9a-9a26-d627c5143bb1)

- Is there any way the user can control the output of base64?
- I've run some tests, and I haven't found any base64 image. I was thinking to update the documentation to reflect this information, unless it's outside out of our control (Google Shopping can return base64 sometimes) 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061004?view=List)

**Comment by ilyazub** [comment]
> Is there any way the user can control the output of base64?

No, SerpApi tries to output URLs for all parsed images. Instead of base64 images, we provide URLs like `https://serpapi.com/searches/65f153ab629a01c3e0d54605/images/ba03583ee6fab58deb5d4a7cf858d8483cfab3237c2276b60cea46382c4e3aa1.jpeg`.

Initially, a couple of customers couldn't use base64 images. Also, base64 image strings were very long, unclean, and fat in the JSON. (Ref: https://github.com/serpapi/SerpApi/issues/95/.)

**Comment by hilmanski** [comment]
Thank you @ilyazub  
Is that mean we should update the document to reflect that as well (to remove that we can provide base64) ?

**Comment by hartator** [comment]
> Is that mean we should update the document to reflect that as well (to remove that we can provide base64) ?

Yes, of course. Feel free to make a PR to do that. 👍
