### ISSUE TITLE
[Youtube API] Wrong subscribers information

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1493]
A user reported that our YouTube API returned the wrong subscriber number information for the `channel_results.` I'm able to replicate it.

Here is an example:
![CleanShot 2024-03-21 at 10 09 16](https://github.com/serpapi/public-roadmap/assets/4522467/51ee6251-c8f9-4aba-90c7-b9506fea80c8)

Another sample:
![image](https://github.com/serpapi/public-roadmap/assets/4522467/ee029008-e855-4f2a-94fe-08f30eb2f74d)

So it looks like when a channel has numbers on its name, we scrape that number instead.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061190?view=List) | [Playground](https://serpapi.com/playground?engine=youtube&search_query=tech+channels&gl=us&sp=SBSCARhVQ0JKeWNzbWR1dllFTDgzUl9VNEpyaVGCAQtGNUFCaTQwSFRyd4IBC3lHWGFBV2J6bDVBggELdUxkc05RRnpNQ3eCAQtNZXZLVFBONG96d4IBC1lMUmRuWHNOVDA4ggELMkN4TmtoR3VwdUGCAQtiMEhmbVk2NGVTRYIBC2ZGT1hqd1BtMnlZggELSnh6SFRVZlZFSlmCAQtjVEhkMERzb1FERYIBGFVDWHVxU0JsSEFFNlh3LXllSkEwVHVud4IBGFVDMTdVd281QmtTVHRHVmJPa3l3SjdfUYIBC1pQdi1lczY2cEFZggELaVRVNjJLMU44QzSCAQswdWlLVGlENWxPMIIBC2dXUzlMWThrMlFnggELRGp2dWxSOE9FZFGCAQtfdXJDeDVVdkVhNIIBGFVDdWNjMFMwRlB5MVdjMXU0Mm9nb0NMd7IBBgoECBoQAuoBBAgCEBk) | [Inspect](https://serpapi.com/searches/65fb968587a0ee8f85d70c10/inspect)

**Comment by btaunt** [comment]
This issue has been resolved. We now extract the correct `subscribers` number:

<img width="1186" alt="Screenshot 2024-03-26 at 10 25 57 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/e63159a5-6913-47ab-8cbd-06576b0aecfa">

## Notes

We now also extract the channel's `handle` and have removed the `video_count` field since Google no longer serves that in their current layouts (they haven't done so for quite some time).

Updated documentation can be found here: https://serpapi.com/youtube-channel-results

[Playground example](https://serpapi.com/playground?engine=youtube&search_query=tech+channels&no_cache=true)
