### ISSUE TITLE
[Google Scholar API] Different quantities of documents in search_information.total_results for the same requests.

### ISSUE THREAD

**Issue by KaluginSlava** [serpapi/public-roadmap#1534]
Example 1:
https://serpapi.com/playground?engine=google_scholar&q=cancer&filter=0&no_cache=true

<img width="1583" alt="Screenshot 2024-04-09 at 5 20 31 PM" src="https://github.com/serpapi/public-roadmap/assets/25756528/e5540bac-9126-4e4e-9898-ca93d5d90950">

**"total_results": 6680000**

Example 2:
https://serpapi.com/playground?engine=google_scholar&q=cancer&num=10&filter=0&no_cache=true

<img width="1581" alt="Screenshot 2024-04-09 at 5 22 39 PM" src="https://github.com/serpapi/public-roadmap/assets/25756528/f557b878-ab41-461c-b515-8e4bcbaeee47">

**"total_results": 6540000**

I need to mention that I cannot replicate this issue consistently, but there are instances where I receive completely different numbers in search_information.total_results, and I cannot find satisfactory explanations for these discrepancies. Please investigate this issue further.

**Comment by schaferyan** [comment]
Thanks for the issue @KaluginSlava. This variation is most likely on Google's side, as Google can sometimes be inconsistent with its estimate for the total number of results available for a query.

Since the inconsistency is coming from Google, there's unfortunately we can do to change it. Due to that, I'm going to close this issue.

However, I do want to note that we appreciate your taking the time to file a complete report, and we hope you won't be discouraged from opening issues in our Public Roadmap in the future, should you encounter other potential bugs.

You are also welcome to reach out to our Customer Success team via **support@serpapi.com** or the chat interface on our website at any time.
