### ISSUE TITLE
[Google Search API] Order pickup/Order delivery link is parsed as `website` in the `knowledge_graph`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1575]
One of our high-volume customers reported that we're parsing the wrong link in the `website` endpoint. It should be a direct link to the business website, but instead, we're parsing the Order pickup/Order delivery Google Food link. I'm marking it as urgent, as it's affecting their business.

Playground example:
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0c36d1a8-8548-4e1c-be51-d641000605bd">

What we're parsing in the `website` field:
<img width="1012" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/567d29b7-9f11-446f-865d-6e25a924fa25">

Where the direct Website link leads to:
<img width="1381" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/72cb00cc-e794-458f-98f9-648e789bb910">

A bit different but similar issue to: https://github.com/serpapi/public-roadmap/issues/1557

[Playground](https://serpapi.com/playground?q=indian+tanpura+new+york+ny+10024&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/662ba5467d171aca53889331/inspect) | [Google search](https://www.google.com/search?q=indian+tanpura+new+york+ny+10024&oq=indian+tanpura+new+york+ny+10024&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064378?view=List)

**Comment by btaunt** [comment]
This has been updated.

We now parse the correct `website` URL on both desktop and mobile, along with targeting the"actionable" buttons for Google's newer layout (ie. `order_pickup` etc.) 

---

<img width="709" alt="Screenshot 2024-05-02 at 9 10 27 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/d3b8e268-697c-4c3a-b73f-1415511d6646">
<img width="670" alt="Screenshot 2024-05-02 at 9 10 37 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/a0b9b34b-e3b6-40be-b6aa-aadd79967a9f">
<img width="776" alt="Screenshot 2024-05-02 at 9 11 18 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/3800c8c0-d492-46ba-ad24-bc02ef3065f1">
<img width="780" alt="Screenshot 2024-05-02 at 9 11 28 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/b28ebe45-9e45-422b-b199-3b06b01af112">

**Comment by schaferyan** [comment]
Thanks @btaunt! The customer noted that it looks like the `website` url is still not being parsed correctly for the original Desktop example:

https://serpapi.com/playground?q=indian+tanpura+new+york+ny+10024&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client

Will that be fixed in the update you mentioned?

I'm re-opening this for now as from the customer's perspective it hasn't been fixed yet.

**Comment by btaunt** [comment]
> Will that be fixed in the update you mentioned?

That's correct @schaferyan - sorry for not being more clear! I will update here once it is live on production 👍

**Comment by schaferyan** [comment]
No worries, thanks @btaunt!

**Comment by btaunt** [comment]
The fix is now live. cc. @schaferyan 

Example searches:

- https://serpapi.com/playground?q=indian+tanpura+new+york+ny+10024&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ie+oe+pws+ibp
- https://serpapi.com/playground?q=Golden+Dragon+800+Wilcox+St+Joliet+IL+60435&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ie+oe+pws+ibp
- https://serpapi.com/playground?q=foot+locker+1460+broadway+ny&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ie+oe+pws+ibp

**Comment by schaferyan** [comment]
Thanks @btaunt !

**Comment by marm123** [comment]
I'm reopening this, as it looks like the issue is still there from time to time. Unfortunately, I wasn't able to recreate it, as it's not consistent, but the customer provided an inspect link, where the issue is present:

[Inspect](https://serpapi.com/searches/666bc9a71c450a9ebab80c1a/inspect)
[Front](https://app.frontapp.com/inboxes/teams/10643996/inbox/open/102866025820)

**Comment by btaunt** [comment]
We have specifically targeted those edge cases (based on the search inspections provided to us). 

The proper `website`  will be parsed for those layouts, if they happen to appear again.
