### ISSUE TITLE
I have to get the Question And Answer? How can i get it.

### ISSUE THREAD

**Issue by umang-varshney** [serpapi/public-roadmap#1609]

**Comment by schaferyan** [comment]
Thanks for this issue @umang-varshney. If this is a problem you've encountered while using SerpApi, or a feature you'd like us to support, can you please provide some more details?

If you are just wondering how to get a part of a search results page, i.e the [Related Questions](https://serpapi.com/google-related-questions-api) block, can you please reach out to **support@serpapi.com**, or contact support through the chat interface? We will be happy to help you there.

I'm closing this for now, since it doesn't seem to be a report of a bug or a feature request.
