### ISSUE TITLE
[Google Shopping API] Return response faster when there are no results.

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1665]
A customer reported that it took a long time to return the result when searching for a specific query on Google Shopping. After checking, I see that Google Shopping itself didn't return a result for this query. I wonder if we can return faster response with specific message rather than a timeout.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067616?view=List) | [Inspect sample](https://serpapi.com/searches/6663f9ecaa6c95ccd570c282/inspect) | [Google Shopping results](https://www.google.com/search?q=best+shoes+2024+near+me&sca_esv=df90e1279361e6f3&sca_upv=1&hl=en&gl=in&tbm=shop&ei=BjtmZsLsG8u-4-EP47W_4AQ&ved=0ahUKEwjCh53R1s-GAxVL3zgGHePaD0wQ4dUDCAg&uact=5&oq=best+shoes+2024+near+me&gs_lp=Egtwcm9kdWN0cy1jYyIXYmVzdCBzaG9lcyAyMDI0IG5lYXIgbWUyBhAAGBYYHkj0ClCmAVjzCXAAeACQAQCYAXagAaIGqgEDNy4yuAEDyAEA-AEBmAIGoAKdBMICBRAAGIAEwgIGEAAYCBgewgIIEAAYFhgKGB6YAwCIBgGSBwM1LjGgB6oX&sclient=products-cc)

**Comment by marm123** [comment]
I don't think the issue is with Google not providing results for that query, as usually, we return an empty successful search if this is the case. The search should not be timing out and returning an error just because there are no results for the query.

I've opened a separate thread for that: https://github.com/serpapi/public-roadmap/issues/1668

**Comment by aciddjus** [comment]
We have fixed this issue. We will now return an empty results error message instead of timing out.

<img width="1543" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/8e738c67-109d-4f7c-9fb4-a9b8c566caf1">


------------------

[Playground](https://serpapi.com/playground?engine=google_shopping&q=best+shoes+2024+near+me&gl=in&hl=en&num=40&device=desktop&no_cache=true)
