### ISSUE TITLE
[Google Shopping Search API] Nothing Found Error Despite Results

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#167]
Google Shopping Search API returns no results error on the Google page while the page has results:

[The Playground](https://serpapi.com/playground?q=iphone&location=France&google_domain=google.fr&gl=fr&hl=fr&tbm=shop) (this will probably work) | [The Inspect](https://serpapi.com/searches/6298aae46073932edd42947a/inspect)

<img width="737" alt="shopping_no_results" src="https://user-images.githubusercontent.com/64849049/171812717-1b2d917c-98e1-4293-bb8b-449e21bec955.png">

Second example:

[The Playground](https://serpapi.com/playground?q=chemise&location=France&google_domain=google.fr&gl=fr&hl=fr&tbm=shop) (this will probably work) | [The Inspect](https://serpapi.com/searches/62994b3717f923126bf80711/inspect)

<img width="739" alt="shoppingnoresult2" src="https://user-images.githubusercontent.com/64849049/171813996-b692f38a-7b6d-4028-bfc4-6583727620e6.png">

We don't know how much Google Shopping Search API is affected and if it affects other APIs due to being proxy related.

**Comment by aciddjus** [comment]
Both playground examples work now. And I don't see any results in the searches you posted, the `no results error` works correctly here. Not sure I get it.

**Comment by aliayar** [comment]
Yeah, both of them are working. However, if you check the inspects, those blank pages happen to come more than occasionally per user's report.

**Comment by aliayar** [comment]
I have run the below script two times:

```
import requests

success = 0
failure = 0
api_key = "YOUR_API_KEY"
news_sample = 'https://serpapi.com/search.json?engine=google&q=iphone&location=France&google_domain=google.fr&gl=fr&hl=fr&tbm=shop&no_cache=true&api_key='


for result in range(0, 100):
    target = requests.get(news_sample + api_key)
    result = target.json()
    
    try:
        print(result['shopping_results'][0]["title"])
        success += 1
        
    except KeyError:
            failure += 1
            print(result['error'])

print(success)
print(failure)
```

The first session ended up with 4 errors while the second one ended with 3 errors.

We have 3-4% of the total requests returning 'not found' error.

**Comment by vlom31** [comment]
We're experiencing the same issue for the past few days, random 0 results from the google shopping Api for very common queries (like "iphone") that we know for sure have responses.. this is very critical for us to fix as we have both investors and media looking at our app at the moment 😞

**Comment by aliayar** [comment]
Conversation 102910000025611 from Intercom states the same is still happening.

[The Inspect ](https://serpapi.com/searches/62a1c9c9303eb1028f4e3a0d/inspect)| [The Playground](https://serpapi.com/playground?q=Fraise+Rouge+Alpille+500g&location=Paris%2C+Paris%2C+Ile-de-France%2C+France&google_domain=google.fr&gl=fr&hl=fr&filter=0&tbm=shop)

However, I am not sure as the Playground link barely finds anything.

**Comment by aliayar** [comment]
I would like to summon @ritu1337. Do you think that this may related to proxies?

**Comment by ritu1337** [comment]
I ran 10,000 searches overnight and got 9 empty results pages, which is much better than the 4-5% (that @aliayar calculated) before disabling Crawlera. I think it's good enough unless we want to retry on empty results. Otherwise, a user can retry themselves.

Empty results pages never happen on serpapi_proxy, probably because it has relatively few IP's compared to millions of IP's that Geosurf has, which could explain how some random IP's give no results.

---

I also once came across this Internal Server Error from Google (I think on `200` status code) on packetstream:
<img width="1062" alt="CleanShot 2022-06-24 at 21 50 21@2x" src="https://user-images.githubusercontent.com/12263752/175657851-f6cf09e3-c929-425c-a970-326e6293f2a1.png">
Google Translate for it is:
> server error
> Sorry, it looks like an internal server error occurred while processing your request. Our engineers have been notified of the issue and are working to resolve it.

I couldn't reproduce this error, saw it only once. I think it was a `200` status code because we returned it as `Fully empty`:
![CleanShot 2022-06-24 at 21 51 31@2x](https://user-images.githubusercontent.com/12263752/175658188-91ccd35c-3180-4a4a-ae46-651b0bff5dec.png)
