### ISSUE TITLE
[Google Search API] `popular_destinations` parsed as `top_sights`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1673]
<img width="1710" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/ef799b32-554d-4e73-bd8d-be13f28a9d90">

[Playground](https://serpapi.com/playground?q=Maldives+Destinations&highlight=popular_destinations&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/666745e7e0ded4d048c28fb4/inspect)

**Comment by aciddjus** [comment]
`short_videos` are also parsed as `top_sights`.

<img width="1511" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/4fd85568-087e-418b-a859-2a3c3ce0d0a9">

[Playground](https://serpapi.com/playground?q=Coffee&device=mobile&no_cache=true&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp) | [Inspect](https://serpapi.com/searches/666978c22fe3026286f60a21/inspect)

**Comment by ishiharaf** [comment]
@kagermanov27 The issue is fixed on production 😺

![image](https://github.com/serpapi/public-roadmap/assets/13112082/6b6e58fa-57c2-4817-8cb5-b247dfc0a162)
[Playground](https://serpapi.com/playground?q=Maldives+Destinations&highlight=popular_destinations&google_domain=google.com)

![image](https://github.com/serpapi/public-roadmap/assets/13112082/73c5b847-7498-49b6-8467-5bd87618d3b0)
[Playground](https://serpapi.com/playground?q=Coffee&device=mobile&no_cache=true&google_domain=google.com)
