### ISSUE TITLE
coffee; PRIORITIZED

### ISSUE THREAD

**Issue by Developmentally-1nSANe** [serpapi/public-roadmap#1711]
[?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en))

>  @[](url)google.com

**Comment by hilmanski** [comment]
Hi, can you please clarify what's your question? We'll be happy to help. You can also contact us at contact(at)serpapi(dot)com.

**Comment by hartator** [comment]
Make sure to close issues that are not completed as "Close as not planned: Won't fix, can't repro, duplicate, stale".

It's messing up our release notes page otherwise (WIP, not in production yet):

![CleanShot 2024-06-24 at 17 27 50@2x](https://github.com/serpapi/public-roadmap/assets/307597/7c88dd6e-5e66-4577-9e5f-2a24454f45c5)

**Comment by Developmentally-1nSANe** [comment]
sorry
