### ISSUE TITLE
[Google Lens API] No results were returned

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1717]
A customer reported that 1/3 of their searches return an empty result.

[Inspect](https://serpapi.com/searches/6679b620116a559482465bee/inspect) | [Result is available in Google Lens](https://lens.google.com/search?p=AbrfA8r0yhO5SfGY2dthVNhm-haDiq02zXAQlqzLIqTaKKuwmVNpDjpQ2Q7b4QcltJB5BphMnWUdXwQL1X7h_7WnfZrNWPReps9_i2GqH3Y-w-M2hgt-tzcwVDSuxp4BmLacFTfidlblI00vnbNBG1PUGILOlEar1FZpvnQ8ihhomaRIfoQryzMBwpwPGIcWJzkm3jmBDieKdnFaLX1yabXb6j9G8BqWVQ7QpMbEvJdmI3c_PU5hEXvHo70YmKpLsnEoCqlBq7J8IV8Djw7tmOEFS6IonP9Yisws-oOl4lFkgxI%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR0ppTURGbE1HTXhMVEE1TkdNdE5ESTNNUzA1TWpKaUxUY3lNelUxWldKak1EUmlZUklmVFhsVVNtZG5NMWhHVlVGVmMwWldkMUYzZG5veE4wWkhObUZJUlVKQ2F3PT0iLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsWyIzZGI2NjgxMi05MDBjLTRkNWEtOTI4MS00NWNiYjY5NzQ0YmEiXV0=) | [Front](https://app.frontapp.com/open/msg_2edznw0s?key=pLn_yV0jtGAk9JdjELWr_g4Eg_gELn2e)

**Comment by andypple83** [comment]
Thanks @hilmanski for reporting this issue. The root cause is that Google Lens can not fetch the image and returns an empty result.

I've run a script to stress test the Google Lens and can not reproduce this error. If this issue reappears, we will push the fix. For now, the engine works as expected.

Let me know if you have more questions! Thanks

**Comment by aciddjus** [comment]
Thanks, @andypple83. If we are not going to work on it, please close the issue as `Close as not planned`.
