### ISSUE TITLE
[Google Jobs API] Results are not returned for many locations

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1826]
One of our customers reported that there are no results for locations that were previously supported. Although I suspect this might be because Google no longer returns any job results with a new layout, I was unable to confirm that with the regular Google search in these locations and make sure it's not an issue on our side. As a side note, I tried multiple combinations with and without `location` and `localization` parameters, and none of them returned any results. Below is the example for Australia (I also tried France and Germany):

<img width="838" alt="image" src="https://github.com/user-attachments/assets/c18be352-f18a-4c26-ab91-cf5d95f38556">

[Playground](https://serpapi.com/playground?engine=google_jobs&q=Barista+job&location=Sydney%2C+New+South+Wales%2C+Australia&google_domain=google.com.au&gl=au&hl=en) | [Inspect](https://serpapi.com/searches/66b22bdfd737d7d117025184/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069237?view=List)

It might be related to https://github.com/serpapi/public-roadmap/issues/1813

**Comment by Freaky** [comment]
I used a web browser through a geolocated Australian proxy and received the same results:

![no-au-jobs](https://github.com/user-attachments/assets/413aa198-b848-4db4-9715-10c58cc2e7ef)

**Comment by arfo90** [comment]
I have been experiencing similar issues since early August, both on serpapi and in my actual browser. Previously, I only needed to set the location, and I could get a list of jobs even using the .com domain. However, currently, for some areas (mainly in the EU), you need to also set their local domain and language for the Google job list to work. In severe cases like this one in Australia, it seems that Google job listings are completely unavailable

I was looking for some related news (anti-trust issue, or sunseting google job, etc) but I couldn't find any as I think it is not related to their new layout but their product strategy change. Was wondering if you have any idea about it and would appreciate if you could share.

**Comment by hartator** [comment]
@arfo90 It's hard to tell. Maybe they have issues sourcing the job posts.
