### ISSUE TITLE
[Google Product API] Scrape a direct `link`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1846]
Currently, we're scraping only the redirect `link` with the Google Product API. With the new layout for Google Shopping API, Google no longer provides a direct link on the shopping page, but according to @aciddjus (ref: https://github.com/serpapi/public-roadmap/issues/1845#issuecomment-2293291021) we can do that on the product page. It's worth implementing as a workaround for customers who require a direct link to a product.

<img width="1670" alt="image" src="https://github.com/user-attachments/assets/e4c54281-98fc-40c3-b59a-f9b7d6122aa9">

[Playground](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/66bf35d68a7c094b7f5de58f/inspect)
[Intercom conversation with the customer who reported missing `link` in Google Shopping API](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069541?view=List)

**Comment by InfiniteCodeMonkeys** [comment]
Please could you prioritize this? The direct product link is the main reason we are using SERP.

**Comment by marm123** [comment]
Thank you for following up @InfiniteCodeMonkeys. We've prioritized the feature and you'll get notified as soon as this is introduced.

**Comment by InfiniteCodeMonkeys** [comment]
Thanks all!

**Comment by aciddjus** [comment]
We have added `direct_link` support for our [Google Product API](https://serpapi.com/google-product-api).

![image](https://github.com/user-attachments/assets/adb8fd3b-c0e7-4d21-851c-02b8930f155a)

**Comment by kingmeers** [comment]
what is the correlation between direct_link on google products api and product_link on google shopping API ? can we trust product_link will remain for the foreseeable future as an available field?

**Comment by schaferyan** [comment]
Hi @kingmeers, the `direct_link` in the Google Product API response provides a direct link to the webpage where the product is found. The `product_link` in the Google Shopping response is a link to Google's product page for that product. Unfortunately, we can't guarantee that Google won't make changes again, as this is beyond our control. However, it seems unlikely that they will stop providing that link via their product page, so even if it changes again we will likely be able to adapt in response.

**Comment by kingmeers** [comment]
> Hi @kingmeers, the `direct_link` in the Google Product API response provides a direct link to the webpage where the product is found. The `product_link` in the Google Shopping response is a link to Google's product page for that product. Unfortunately, we can't guarantee that Google won't make changes again, as this is beyond our control. However, it seems unlikely that they will stop providing that link via their product page, so even if it changes again we will likely be able to adapt in response.

I understand that it was unprecedented but the fact that the direct link now costs a credit to retrieve, in cases where we use 100 credits to get 100 results from shopping api, each yielding 60 products, now costing us **6000** credits instead of 100 to get the full picture is a bit terrifying and has got my team and I scrambling for ways to circumvent this new limitation. 

I've spoken with support and it really seems as though spending 61 credits on a call previously costing 1 credit to get the data we require is the only proposed solution thus far. I don't know what your profit margin is but I wonder if there is some ID you can retain from each product that is directly correlated to the domain, that you can then provide to us, but I cannot justify spending 6000 credits, where I expected to spend 100.

**Comment by schaferyan** [comment]
>I don't know what your profit margin is but I wonder if there is some ID you can retain from each product that is directly correlated to the domain, that you can then provide to us, but I cannot justify spending 6000 credits, where I expected to spend 100.

First, I do want to acknowledge the inconvenience and offer our sincere apology. Unfortunately, I don't believe such an ID exists. 

If you visiti a [Google Shopping page](https://www.google.com/search?sca_esv=7ccaf3fd733f8b3e&sca_upv=1&q=tv&udm=28&fbs=AEQNm0AVbySjNxIXoj6bNaq7uSpw-2eW7KIQ8H4T_tEPJYsPzCcvIbeL0sDwK4orswBP0Nc8uQ9LDhT0yg-pvDPpZ9jXUDUY5t2AeDAM6KJotTNXWgOFF5WBdyVEnuPA_xmbCU994alMcBCpuU3GxJ4DGed9j9glSP7EJwfWxpB4glKvU7Zc_MU_lzSdehs3hizX1UXGn0hK9Z83OqM7iJCh9gmT1nLTrQ&ved=1t:220175&ictx=111&biw=1901&bih=997&dpr=1.5) now, you will see that you can't navigate to the domain where the product is found without first opening the Google Product page.

In order to get the link for each product, we would effectively have to call the Product API on our side for every result returned in a Google Shopping response, which would be both expensive and inefficient. This would require us to increase the price for all SerpApi users. Since we prefer a simple pricing model that transparently reflects individual usage, that's unfortunately not something we can do.
