### ISSUE TITLE
No more "link" on product means finding seller's store URL costs 60x as much for 60 product queries

### ISSUE THREAD

**Issue by kingmeers** [serpapi/public-roadmap#1849]
We use SerpAPI to get product links from results and analyse certain factors, and now we have to use Product API to get the direct link, for each product by id, costing 60 credits for 60 products?

I use about 100 credits a day during testing, that would now become 6000 credits for my case, I really hope I'm mistaken and have missed something, 

Google shopping API does not even provide the source url for the store, just the "source" name, but Walmart/Amazon etc. have hundreds if not thousands of different "seller names" on the same domain, so we can't even use that field to deduce similarly owned products, this is a huge deal, has anyone figured out any smart ways to circumvent this?

**Comment by schaferyan** [comment]
As noted on https://github.com/serpapi/public-roadmap/issues/1846 since Google doesn't provide a direct link to products in the US Google Shopping layout anymore, this is unfortunately not possible without either using a different `gl`, or accessing the Google Product Pages. In order to keep things transparent and simple, we unfortunately need you to use the Google Product API to access those pages via our API.

Again, we're very sorry about this and we're grateful for your patience.

**Comment by schaferyan** [comment]
@kingmeers I've re-opened #1845, which would resolve this. Note that there is still no guarantee, but there is an open PR to add a new parameter to the Google Shopping API, which would enable one additional call on our side per Google Shopping API search to get and return the link as before.

**Comment by kingmeers** [comment]
Any update?

**Comment by hilmanski** [comment]
We're still working towards a solution. Feel free to follow this thread: https://github.com/serpapi/public-roadmap/issues/1845. We'll let you know when there's any update. Thank you very much for your patience!

**Comment by marm123** [comment]
Following up here with a note from our Senior Engineer @tanys123:

>We have made a new release that adds link to Google Shopping API. You have to enable it by passing direct_link=true. Feel free to try it out and feedback to us.
![image](https://github.com/user-attachments/assets/0aa2488c-a130-4f7f-9207-4cca449fe68e)

Tagging for visibility @kingmeers 

Fee free to reach out with any questions or concerns. We'll be happy to assist!

**Comment by kingmeers** [comment]
> Fee free to reach out with any questions or concerns. We'll be happy to assist!

That's awesome! Does it cost any extra credits per call? Also, is this essentially the original response exactly, just now requiring the direct_link=true passed?

**Comment by NateSkiles** [comment]
@kingmeers 
> Does it cost any extra credits per call? 

No, we are committed to maintaining the cost of a single search to one search credit. Adding `direct_link=true` will not cost any additional credits.

> Also, is this essentially the original response exactly, just now requiring the direct_link=true passed?

The direct `link` returned is the same as the original response, but we have added some additional `links` Google includes in the response.

**Comment by sonika-serpapi** [comment]
@kingmeers 
While it doesn't cost any extra credits, I want to also mention that the API calls with the `direct_link` parameter might take longer than without. This is because of the different approaches we have to take to extract the link and links values. This, unfortunately, puts a heavier load on our backend, which might result in a decreased performance in terms of response times. I'm very sorry in advance if that's the case, and I hope you understand.

**Comment by kingmeers** [comment]
> The direct `link` returned is the same as the original response, but we have added some additional `links` Google includes in the response.

This is great, is this because google added back the product links or because of a workaround built by your team? Basically, are you technically calling the product api every time i call an endpoint with `direct_link=true` ?

**Comment by sonika-serpapi** [comment]
@kingmeers We are recovering these links using another one of Google's endpoints, which requires an additional request from us. Google has not restored the the product links on their end for the google shopping page.

**Comment by kdmny** [comment]
I'm curious, how often are you seeing searches that use the `direct_link` parameter return responses with the `link` property in the results? Anecdotally, I've seen ~50% of my searches where I set `direct_link=true` come back without any `link` property, here's one such example:

https://serpapi.com/searches/43fec90a89ed7180/67a624233d07d2bcd103f8ad.json

**Comment by alexbarron** [comment]
> I'm curious, how often are you seeing searches that use the `direct_link` parameter return responses with the `link` property in the results? Anecdotally, I've seen ~50% of my searches where I set `direct_link=true` come back without any `link` property, here's one such example:
> 
> https://serpapi.com/searches/43fec90a89ed7180/67a624233d07d2bcd103f8ad.json

Thanks for writing in @kdmny . It's hard to answer your question because it really depends on which products someone is searching for. 

Note that we're discussing the issue on this thread instead: https://github.com/serpapi/public-roadmap/issues/1889

Sorry that this is impacting you! We hope to have a better solution or recommendation on next steps soon.

**Comment by leibel-reco** [comment]
It seems that the immersive product api is not very gated by google. It is a very quick response. 

Is there any way to make those requests cheaper than 1 credit?

I have the same issue where I need a product link for each of the search results and it would become untenable to pay one credit for each result

**Comment by schaferyan** [comment]
Hi @leibel-reco - thanks for your thoughts on this.

Unfortunately, we won't be able to make those requests cost less than a credit, as it's our policy that every API call costs exactly one credit.

I recommend reaching out to us at contact@serpapi.com for concerns about the increased cost.
