### ISSUE TITLE
[Google Product API] Intermittent Broken Direct Link 

### ISSUE THREAD

**Issue by InfiniteCodeMonkeys** [serpapi/public-roadmap#1860]
Hey Team, 

The Google Product API is intermittently returning broken URLs for some product links: 

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/753a94b2-21db-4d1f-a1df-9bd150c7872b">

Is there anything you can do to ensure the links are working correctly?

**Comment by schaferyan** [comment]
Thanks for the issue, @InfiniteCodeMonkeys. We will look into this, thank you so much for your patience in the meantime!

**Comment by schaferyan** [comment]
An [Enterprise Customer](https://app.frontapp.com/open/msg_2h59p4po?key=DRhiDxTTrP0sEC8dGCYGgStkixcmeUIF) also reported this.

**Comment by sonika-serpapi** [comment]
Thank you @kingmeers

**Comment by aciddjus** [comment]
Outside of fixing these links by adding the domain in front of it, Google Shopping does not return the direct source link in these cases.

The best we could do is to add support for scraping the [Google Shopping direct link](https://www.google.com/shopping/product/17931014727557903579?hl=en&prds=pid:8266316953725460760&sts=9&lsf=seller:102213865,store:6931734313095491136) page. Which would be a new API request.


![image](https://github.com/user-attachments/assets/1d6f9512-de9a-4b3a-93e4-41ea24f0a08d)

**Comment by schaferyan** [comment]
Thank you @aciddjus. The Enterprise customer who reported this asked us if we could do a url validation, if the issue is on Google's side. So they may just be looking for some indicator that the direct link isn't available, instead of getting back a broken link.

I'll follow up though to see if support for the Google Shopping direct link page would be helpful for them.

**Comment by aciddjus** [comment]
@schaferyan Can we first clarify what they mean by "broken link"? Is it that the link is not working because of the lack of domain or because the link is not a direct source but leads to another Google Shopping page?

- If it's the first issue, we just need to add a domain to make the link work.
- If it's a second issue, we could simply not extract those links (but I'm not super in favor of this as they still fall into `direct_link` category; if we called the field `source_link`, it would made more sense to not have them there), or they could validate on their side and just check if the link starts with `{google_domain}/shopping/product/`.

**Comment by InfiniteCodeMonkeys** [comment]
The broken links we saw were missing domains.

**Comment by aciddjus** [comment]
Thank you for the additional feedback, @InfiniteCodeMonkeys. Again, we apologize for the inconvenience.

**Comment by schaferyan** [comment]
Thank you @aciddjus 

>@schaferyan Can we first clarify what they mean by "broken link"? Is it that the link is not working because of the lack of domain or because the link is not a direct source but leads to another Google Shopping page?

My assumption based on the context is that by broken they mean the links can't be opened because they're missing the domain. But I've followed up with them to clarify that.

**Comment by mikemorcerf** [comment]
This issue has been fixed.

**Comment by aciddjus** [comment]
Thanks, @mikemorcerf. Make sure to add a screenshot of the playground as well, with the working code

**Comment by mikemorcerf** [comment]
Thank you @aciddjus 

Below are images of Before and After the fix for the same product:
Here's an image of before fixing:
![Screenshot 2024-09-16 at 10 51 02 AM](https://github.com/user-attachments/assets/2d9ad242-74e8-4086-9e34-cc7bd9b1cc02)

After the fix:
![Screenshot 2024-09-16 at 10 52 34 AM](https://github.com/user-attachments/assets/ee2b12d5-5695-41d0-89b5-fd0f1920258e)
