### ISSUE TITLE
[Google Jobs API] Google search results shown in playground browser window for some countries

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2040]
A customer reported that the playground browser window shows results from Google search instead of Google jobs. The returned JSON is different from what's shown on the browser window, and shows no results were found. The Search Engine Query link is also for Google search. 

<img width="1026" alt="Screenshot 2024-10-16 at 11 32 36 AM" src="https://github.com/user-attachments/assets/9a85b634-3547-4bde-8d3f-f602fd8b2fbb">

The customer reported they are seeing this issue with specific countries:

Ireland
Norway
Sweden
Denmark
Luxembourg

Public links: [Playground](https://serpapi.com/playground?engine=google_jobs&q=data+scientist&location=Ireland&google_domain=google.ie&gl=ie&hl=en&newPara=tbs)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060751?view=List) | [Search Inspect](https://serpapi.com/searches/670ffd1389055ec66e603b4d/inspect)

**Comment by hilmanski** [comment]
I suspect this is Google's actual behavior.

Test results on accessing this link `https://www.google.com/search?q=jobs%20near%20me&jbr=sep:0&udm=8`

Test 1 (Jobs result, VPN: Argentina)
![CleanShot 2024-10-17 at 06 28 50](https://github.com/user-attachments/assets/d1535951-5b53-445f-8ee6-074b1ef8944a)

Test 2 (Organic results, VPN: Ireland)
![CleanShot 2024-10-17 at 06 30 07](https://github.com/user-attachments/assets/acf91fb8-d01f-4db5-ba17-72e71756b54a)

Test 3 (Jobs Result, VPN: Denmark)
![CleanShot 2024-10-17 at 06 31 35](https://github.com/user-attachments/assets/9faa2af9-6f17-4bde-95b3-7f6d77aa5bad)

Using Denmark in Playground should show the result as well: https://serpapi.com/playground?engine=google_jobs&q=jobs+near+me&location=Denmark&google_domain=google.dk&gl=dk&hl=da&newPara=next_page_token

**Comment by schaferyan** [comment]
Yes, looks like Google Jobs is not available in these countries. 

Looking at this [Ireland search](https://www.google.ie/search?q=data+scientist&uule=w+CAIQICIHSXJlbGFuZA&hl=en&gl=ie&udm=8) it appears there is no "Job" tab, and `8` is not a valid value for `udm`:

<img width="1317" alt="Screenshot 2024-10-18 at 12 37 05 PM" src="https://github.com/user-attachments/assets/5e7ea812-68b1-4806-996a-0e882dc10804">

Also found this list of countries where Google Job postings are supported:

https://developers.google.com/search/docs/appearance/structured-data/job-posting#region-availability

I'm closing this as not planned, since this is on Google's side. 

We can consider clarifying in the documentation for the Google Jobs API that Google supports Jobs for a limited selection of countries.

**Comment by schaferyan** [comment]
Yes, looks like Google Jobs is not available in these countries. 

Looking at this [Ireland search](https://www.google.ie/search?q=data+scientist&uule=w+CAIQICIHSXJlbGFuZA&hl=en&gl=ie&udm=8) it appears there is no "Job" tab, and `8` is not a valid value for `udm`:

<img width="1317" alt="Screenshot 2024-10-18 at 12 37 05 PM" src="https://github.com/user-attachments/assets/5e7ea812-68b1-4806-996a-0e882dc10804">

Also found this list of countries where Google Job postings are supported:

https://developers.google.com/search/docs/appearance/structured-data/job-posting#region-availability

I'm closing this as not planned, since this is on Google's side. 

We can consider clarifying in the documentation for the Google Jobs API that Google supports Jobs for a limited selection of countries.

**Comment by schaferyan** [comment]
Yes, looks like Google Jobs is not available in these countries.

Looking at this [Ireland search](https://www.google.ie/search?q=data+scientist&uule=w+CAIQICIHSXJlbGFuZA&hl=en&gl=ie&udm=8) it appears there is no "Job" tab, and 8 is not a valid value for udm:

Screenshot 2024-10-18 at 12 37 05 PM
Also found this list of countries where Google Job postings are supported:

https://developers.google.com/search/docs/appearance/structured-data/job-posting#region-availability

I'm closing this as not planned, since this is on Google's side.

We can consider clarifying in the documentation for the Google Jobs API that Google supports Jobs for a limited selection of countries.

**Comment by schaferyan** [comment]
Yes, looks like Google Jobs is not available in these countries.

Looking at this [Ireland search](https://www.google.ie/search?q=data+scientist&uule=w+CAIQICIHSXJlbGFuZA&hl=en&gl=ie&udm=8) it appears there is no "Job" tab, and 8 is not a valid value for udm:

<img width="1321" alt="Screenshot 2024-10-18 at 12 38 16 PM" src="https://github.com/user-attachments/assets/ce33b8b9-43be-4064-90fc-36b55a4775e0">

Also found this list of countries where Google Job postings are supported:

https://developers.google.com/search/docs/appearance/structured-data/job-posting#region-availability

I'm closing this as not planned, since this is on Google's side.

We can consider clarifying in the documentation for the Google Jobs API that Google supports Jobs for a limited selection of countries.
