### ISSUE TITLE
[Google Trends API] Don't return anymore  data with categorie

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2051]
Hi,

It appears that your API is currently no longer returning data with cat parameter (until yesterday all was fine).

![image](https://github.com/user-attachments/assets/bd973b1b-9ad3-46fd-b083-55f8e38ef77f)

https://serpapi.com/playground?cat=238&data_type=RELATED_QUERIES&date=today+1-m&engine=google_trends&geo=FR&hl=fr&tz=120

Is it from your side ?

Any solution ?

regards

**Comment by martin-serpapi** [comment]
Hi @RedBillyOne , thank you for reporting the issue, and apologies for the inconvenience.

This seems to have been a temporary issue as I'm receiving a successful response from the Google Trends API for requests with the exact same parameters you've shared (I've tested sending over 30 requests):

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/04f50380-0be2-435c-8f2a-469c84c6b81d">

[Playground](https://serpapi.com/playground?engine=google_trends&hl=fr&geo=FR&data_type=RELATED_QUERIES&tz=120&cat=238&date=today+1-m&no_cache=true) | [Inspect](https://serpapi.com/searches/671914afa869210cd06b241c/inspect)

Can you please confirm if you're receiving a successful response for this search query now?

Meanwhile, our team will investigate the issue further.

**Comment by schaferyan** [comment]
This [example](https://serpapi.com/playground?cat=238&data_type=RELATED_QUERIES&date=today+1-m&engine=google_trends&geo=FR&hl=fr&tz=120) still seems to be failing.  However, I believe it may just be that there are currently no related queries for "coffee" in the "Cosmetic Surgery" category, as other query and category pairings seem to work: 

https://serpapi.com/playground?engine=google_trends&q=Coffee&hl=fr&geo=FR&data_type=RELATED_QUERIES&tz=120&cat=3&date=today+1-m&no_cache=true

Also, when I try providing this category in a Google Trends search for "coffee in the browser, it also returns empty:

https://trends.google.com/trends/explore?cat=238&date=now%201-d&geo=US&q=coffee&hl=en

<img width="1219" alt="Screenshot 2024-10-23 at 2 30 35 PM" src="https://github.com/user-attachments/assets/dcc7d948-677a-4934-89f5-44cc5303a75e">

@RedBillyOne can you provide an example of a category search that works with Google Trends in the browser, but not when using the API?

If not, I think we can close this issue, since it doesn't seem to be due to a problem with the API.

**Comment by RedBillyOne** [comment]
Hi,

I confirm all is fine now.

Thanks.
________________________________
De : Martin Kaldramov ***@***.***>
Envoyé : mercredi 23 octobre 2024 17:33
À : serpapi/public-roadmap ***@***.***>
Cc : RedBillyOne ***@***.***>; Mention ***@***.***>
Objet : Re: [serpapi/public-roadmap] [Google Trends API] Don't return anymore data with categorie (Issue #2051)


Hi @RedBillyOne<https://github.com/RedBillyOne> , thank you for reporting the issue, and apologies for the inconvenience.

This seems to have been a temporary issue as I'm receiving a successful response from the Google Trends API for requests with the exact same parameters you've shared (I've tested sending over 30 requests):

image.png (view on web)<https://github.com/user-attachments/assets/04f50380-0be2-435c-8f2a-469c84c6b81d>

Playground<https://serpapi.com/playground?engine=google_trends&hl=fr&geo=FR&data_type=RELATED_QUERIES&tz=120&cat=238&date=today+1-m&no_cache=true> | Inspect<https://serpapi.com/searches/671914afa869210cd06b241c/inspect>

Can you please confirm if you're receiving a successful response for this search query now?

Meanwhile, our team will investigate the issue further.

**Comment by hilmanski** [comment]
Thank you very much for your update, @RedBillyOne . Just let us know if you reencounter this issue.

**Comment by RedBillyOne** [comment]
Hi,

We've got a new error

https://serpapi.com/playground?cat=122&data_type=RELATED_QUERIES&date=today+1-m&engine=google_trends&geo=FR&hl=fr&tz=120
or this one
https://serpapi.com/playground?engine=google_trends&hl=fr&geo=FR&data_type=RELATED_QUERIES&tz=60&cat=122&date=today+1-m

![image](https://github.com/user-attachments/assets/4974a04c-9692-44e0-ba04-a565a92182bb)

Is it from your Side ?

Any solution to solve this ?

Regards

**Comment by hilmanski** [comment]
Hi @RedBillyOne thank you very much for your report; we'll investigate this.

[Inspect](https://serpapi.com/searches/671ebb9ea2e99c5188ae46e4/inspect) | [Inspect](https://serpapi.com/searches/671ebba3671f3ff07f1a4dba/inspect)
