### ISSUE TITLE
[Google Search API] Fully empty result on a valid search

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2087]
A customer reported that their search returned empty results days ago but returned valid results today.

Failed search:
![image](https://github.com/user-attachments/assets/bacd3ee4-53ff-4aca-afb8-f448498ce0ff)

Successful search with the same parameters:
![image](https://github.com/user-attachments/assets/7bae9c4f-dbf4-479a-adf0-8e202ecccb4a)

Public: [Plaground](https://serpapi.com/playground?device=desktop&engine=google&gl=jp&google_domain=google.com&location=Japan&q=%E4%B8%AD%E7%9A%AE%E8%85%AB%E8%A3%81%E5%88%A4+%E6%9C%80%E6%96%B0%E6%83%85%E5%A0%B1)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000071771) | [Failed Search](https://serpapi.com/searches/6725e8c5ba1142c52cec87fc/inspect) | [Successfull Search](https://serpapi.com/searches/67282b60577da5dbe1dd9969/inspect)

**Comment by hilmanski** [comment]
The customer reached out again, asking about this issue.

**Comment by Krugloff** [comment]
Wow, the failed search returned a 500 Internal Server Error.

**Comment by Krugloff** [comment]
@hilmanski I'm not sure if the customer is encountering this issue again or just inquiring about it. The failed request used the proxy provider zyte_api_datacenter, while the successful request used lightning_proxies. Is it possible this issue is related to the Zyte proxy, which we have already attempted to address?
