### ISSUE TITLE
Add exhausted searches error to the `Errors` documentation page

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#2173]
A user requested that we add an exhausted searches error to our `Errors` documentation page. Currently, this is missing:

![image](https://github.com/user-attachments/assets/3df34a6e-6f6a-49d8-af7d-c0bf37ed4430)

[Errors](https://serpapi.com/api-errors)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056793?view=List)

**Comment by hartator** [comment]
@tanys123 @schaferyan There is several other issues with these new error pages:
- "In general, codes in the 2xx range indicate success." I don't think we have a case with other 2xx than `200`.
- The icon and the name of the page is a little scary. I thought something was wrong with SerpApi when I first encoutered the new page inside that left menu:
![CleanShot 2024-11-27 at 16 50 53@2x](https://github.com/user-attachments/assets/6b066efe-8fb6-4194-baf9-dec797c41f90)
Maybe we can find a less warning-ly icon if that makes sense? And maybe rename this page to "Handled API Errors" or "Error Codes and Responses" or "API Troubleshooting"  or "API Error Reference" or "API Error Reference" or something in the like (a little tired mostly inspired by ChatGPT but maybe we can also look at Stripe and others to see how they name these pages)?
- Pages are broken on mobile, you shouldn't have to left scroll for text content:

![CleanShot 2024-11-27 at 16 58 21@2x](https://github.com/user-attachments/assets/86d565e2-1b54-446d-8ab1-1aa4f6eee3b9)
- Maybe let's make these pages less prominent as most of our users should be able to use fully the API without encountering any errors (anything actually blocking is an email that's not related to queries), like maybe under "Extra APIs" or a subpage somewhere else?

Maybe let's revert and republish; or address these issues soonish?

**Comment by dsojevic** [comment]
@hartator, I've got [a draft PR](https://github.com/serpapi/SerpApi/pull/5594) with some adjustments/fixes for most of what you've mentioned here:

> * "In general, codes in the 2xx range indicate success." I don't think we have a case with other 2xx than `200`.

Adjusted to refer to `200` only in the PR

> * The icon and the name of the page is a little scary. I thought something was wrong with SerpApi when I first encoutered the new page inside that left menu:
>   Maybe we can find a less warning-ly icon if that makes sense? And maybe rename this page to "Handled API Errors" or "Error Codes and Responses" or "API Troubleshooting"  or "API Error Reference" or "API Error Reference" or something in the like (a little tired mostly inspired by ChatGPT but maybe we can also look at Stripe and others to see how they name these pages)?

In terms of naming, here are a few examples from popular services:
| Service | Page Name |
| - | - | 
| Stripe | [Errors](https://docs.stripe.com/api/errors) |
| PayPal | [API Responses](https://developer.paypal.com/api/rest/responses/) |
| AWS | [Common Errors](https://docs.aws.amazon.com/apigateway/latest/api/CommonErrors.html) |
| eBay | [Handling Errors](https://developer.ebay.com/api-docs/static/handling-error-messages.html) |
| Azure | [Getting Started with REST](https://learn.microsoft.com/en-us/rest/api/azure/#components-of-a-rest-api-requestresponse) _(status codes mentioned as subitem on page)_ |

My personal preference would be to use "API Responses" because we also describe `200` status codes here.

> * Maybe let's make these pages less prominent as most of our users should be able to use fully the API without encountering any errors (anything actually blocking is an email that's not related to queries), like maybe under "Extra APIs" or a subpage somewhere else?

It might be worth adding a "Getting Started" page that contains the current error code pages and it can also include other details that are common across all of the APIs such as authentication, no cache, etc.

This would remove the scarier "error" type headings from the top level and would also serve as a decent/obvious landing point for those clients who may not be regular consumers of APIs.

> * Pages are broken on mobile, you shouldn't have to left scroll for text content:

Have adjusted this in the PR and its significantly better, but still needs some tweaking to cover the resolution used in your example.

**Comment by tanys123** [comment]
We have updated the documentation to include the Exhausted Searches error and made a few other improvements to ensure it is clearer and easier to navigate.

<img width="1350" alt="Screenshot 2024-12-16 at 9 48 52 AM" src="https://github.com/user-attachments/assets/b11fc38c-57f7-447c-a47f-716386fce8ec" />

[Status and Error Codes Documentation](https://serpapi.com/api-status-and-error-codes)
