### ISSUE TITLE
[Google Ads Transparency Center API] Images not shown in playground

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2181]
A user reached out, reporting that the images returned in searches are not displaying in the playground:

![image](https://github.com/user-attachments/assets/3904ac4d-3f06-4610-8a3c-b28f2eb46a46)

[Playground](https://serpapi.com/playground?engine=google_ads_transparency_center&advertiser_id=AR17828074650563772417&region=2840&no_cache=true) | [Inspect](https://serpapi.com/searches/67477d915416d8806ec15e4e/inspect)

Based on our [documentation](https://serpapi.com/google-ads-transparency-center-api#api-examples-example-with-advertiser-id-ar17828074650563772417-tesla-inc), it looks like these used to be displayed in the HTML preview:

![image](https://github.com/user-attachments/assets/5f5d9d74-ee1a-4bf7-bd71-c2da7dde9f64)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072579?view=List)

**Comment by marm123** [comment]
Hmmm, it works for me, and I also see them on the Inspect link you shared @NateSkiles. Maybe some of your local settings are preventing loading them since these are not the images but iframes loaded via separate JS file ([reference](https://github.com/serpapi/public-roadmap/issues/1721#issuecomment-2208354242)). Not sure, just leaving it here in case it helps troubleshoot the issue.

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/90ab3639-7e8f-4fce-9fda-4d5f9f5863b0">

**Comment by NateSkiles** [comment]
@marm123 Thanks for this! I was wondering if that was the case. I tried with Google and Firefox in incognito, and assumed something was wrong.

It turns out I have uBlock enabled in incognito across both browsers; disabling resolves this. 🤦🏻‍♂️

Who would have thought the ad blocker would be why I can't see the ads? Closing this.
