### ISSUE TITLE
[Bing Search API] Most of `organic_results` are scraped as `ads`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2198]
Our Enterprise Customer reported they are getting `organic_results` in `ads` block. I've been able to recreate that.

This is 19th result in `ads`:
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/90211a1e-5d4e-4dcc-a372-8c55b9891de2">

Only 2 `organic_results` scraped:
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/f163b3e4-55a7-48cb-a34d-18473a754ad4">

Public links: [Playground 1](https://serpapi.com/playground?engine=bing&q=Coffee&cc=US&device=desktop)

Internal links: [Front](https://app.frontapp.com/open/cnv_1e339icc) | [Search Inspect - Coffee](https://serpapi.com/searches/67515976d403e1274bc047f2/inspect) | [Search Inspect - customer's search](https://serpapi.com/searches/6750a079ee677f86e8a556df/inspect)

**Comment by tanys123** [comment]
There are indeed _sponsored_ results. The tag got removed after processing from our side but when looking at the HTML directly, all the results are tag with _sponsored_. The link is also a Bing tracking link instead of direct link. Perhaps a Bing issue or we have to look further to see why more ads results are returned.

https://github.com/user-attachments/assets/fade5f62-8213-45f4-89e1-68f1a36a2fe9

**Comment by marm123** [comment]
Nice catch, thank you @tanys123! I'll let the customer know that these are considered `ads`. Do you think we should perhaps open a separate thread to include the `sponsored` tag on the HTML so it's clearly visible to the customer?

**Comment by marm123** [comment]
I'm closing it as not planned and in favor of
