### ISSUE TITLE
[Google Search API] No organic_results included in JSON for mobile search

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2224]
A customer reported a one-off Google mobile search where the HTML preview shows organic results, but `organic_results` were not included in the JSON. The customer didn't encounter this any other times, and I haven't been able to reproduce it.

![image](https://github.com/user-attachments/assets/26254959-f9dd-4dfd-95cf-b89f9ba7c54e)

Public links: [Playground](https://serpapi.com/playground?q=slot+gacor&location=Indonesia&google_domain=google.co.id&gl=id&hl=id&num=100&device=mobile&no_cache=true&newPara=as_sitesearch+chips+as_qdr)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073035?view=List) | [Search Inspect](https://serpapi.com/searches/675ade9b9e4a36719a80c349/inspect)

**Comment by NateSkiles** [comment]
This customer reached out again with another example:

[Search Inspect](https://serpapi.com/searches/675b377594adca14d41de623/inspect)

---

I was able to reproduce this a couple times:
* [Search Inspect 1](https://serpapi.com/searches/675b3e4f8733edc073efb8aa/inspect)
* [Search Inspect 2](https://serpapi.com/searches/675b3f486f4dd1a7632bee28/inspect)

All of these requests went through the same proxy provider and appear to be returning desktop results instead of mobile.

Requests through other proxy providers appear to be fine:
* [Working Search Inspect](https://serpapi.com/searches/675b3f9ce68326ef0b32ec56/inspect)

**Comment by schaferyan** [comment]
A few other examples:

[Inspect 1](https://serpapi.com/searches/675b429135bad404545bf16b/inspect) | [Inspect 2](https://serpapi.com/searches/675b42f568a9a1a0c1a8b67e/inspect)

All of these examples also have `location: Indonesia` and `num=100`.

**Comment by zyc9012** [comment]
Extraction failed because desktop versions were returned instead of mobile ones.

**Comment by dsojevic** [comment]
From some initial exploration in my local environment, this appears to be occurring 100% of the time with the proxy provider in question for any Google searches using `mobile` or `tablet` for the device.

Going to investigate further, but I suspect that this current PR is somewhat relevant: https://github.com/serpapi/SerpApi/pull/5605

**Comment by dsojevic** [comment]
This issue should be resolved now; the upstream provider has since fixed the regression that was causing this.

**Comment by alexbarron** [comment]
Thanks @dsojevic !
