### ISSUE TITLE
[Google Search API] Inconsistent results

### ISSUE THREAD

**Issue by jan-koz** [serpapi/public-roadmap#250]
Hello, another problem with search api. Two searches with exactly same "search_parameters" gives different results:
![image](https://user-images.githubusercontent.com/56533850/182600433-448199ee-41c0-4b32-9f6f-9f0c7bbd3349.png)

![image](https://user-images.githubusercontent.com/56533850/182600531-35024e3c-fa6a-4956-8a5a-a3dd4d87938e.png)

Only second search contains "product_result" key, although parameters of the searches are exactly the same so the output should be the same as well

**Comment by aliayar** [comment]
Hi @jan-koz 

Thank you for your report. 

This is due to fact that you use a very general location. When you do that, Google tries to give you an exact location using the IP address. As each request uses a different IP address but the same generic location with all other parameters being the same, Google differentiates results according to the IP address.

If you use a more precise location, your results may still vary. But at that point, it is Google's preference to show extra elements or not:

![image](https://user-images.githubusercontent.com/64849049/182604993-bd7a7da8-c2a9-4d5e-92df-c3a9b3a73207.png)


![image](https://user-images.githubusercontent.com/64849049/182604916-0ac67f6b-1f65-4a57-bf59-85f969059e11.png)
