### ISSUE TITLE
[Yahoo Search API] Only first line of a list is parsed for some mobile `organic_results`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#295]
![yahoo_2](https://user-images.githubusercontent.com/73674035/187538043-3b21a05c-579d-4c17-96cb-1ed0f3da8161.png)
[Playground](https://serpapi.com/playground?engine=yahoo&p=Coffee&pz=100&device=mobile&no_cache=true)
[Inspect](https://serpapi.com/searches/630e73dc58762b51256bb370/inspect)

**Comment by btaunt** [comment]
This issue has been fixed, along with additional QoL changes:

- New `snippet_list` key for snippets containing list items
- New `snippet_highlighted_words` for highlighted words inside snippets
- New `tabbed_content` since this is custom enough to fall *outside* of snippets
  - Each includes `title`, `content`, `link`
  
<img width="645" alt="Screenshot 2024-03-11 at 12 50 34 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/f45ff65b-a584-49c1-a9b5-87e166cb415f">
<img width="732" alt="Screenshot 2024-03-11 at 12 51 31 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/6541a36b-8d48-4584-a8a7-320df7354317">
<img width="683" alt="Screenshot 2024-03-11 at 12 50 56 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/95abf8b6-131a-4857-826e-d105fb123af3">
