### ISSUE TITLE
[Baidu Answer Box API] Add support for line chart answer box

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#48]
Add support for population answers. e.g. "population of China"

Playground: https://serpapi.com/playground?engine=baidu&q=%E4%B8%AD%E5%9B%BD%E4%BA%BA%E5%8F%A3

<img width="606" alt="Screenshot 2022-03-08 132727" src="https://user-images.githubusercontent.com/6929257/157238109-4559a6d6-7210-41d2-a48c-8f6e73d84b20.png">

**Comment by kagermanov27** [comment]
This is a general answer box for line charts rather than only population. 
[Example (Chinese GDP)](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E4%B8%AD%E5%9B%BD%E5%9B%BD%E5%86%85%E7%94%9F%E4%BA%A7%E6%80%BB%E5%80%BC&fenlei=256&oq=%25E4%25B8%25AD%25E6%2596%2587%25E8%25AF%2586%25E5%25AD%2597%25E7%258E%2587&rsv_pq=fcbeb2fc0001004a&rsv_t=3bb3Dj%2BsEKZpWZNiWU9bAD%2F%2FTqgx%2F6UA2eSNZDVJip73y0%2BajGp1WhpcG5s&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&inputT=901&rsv_sug3=6&rsv_sug1=4&rsv_sug7=100&rsv_n=2&rsv_sug2=0&rsv_sug4=1022&rsv_sug=1)
