### ISSUE TITLE
[Google Play API] Searches time out with "Failed to retrieve HTML." error.

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#481]
This issue appears when there are a few parameters included - `"gl",` `"store": "movies"` and `"movie_category": "MOVIE"`. This is not the case for all gl parameters as it works fine with for example `us` and `fr`, but doesn't work with others (tested `es`, `pl`, `br`). I also tested different parameters and the issue was only present for the ones I mentioned above (probably didn't test all combinations though).

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/28161162/200511139-bdf6547b-94a3-4440-8afa-f0a1c86491ca.png">

BR: <a href="https://serpapi.com/playground?engine=google_play&gl=br&store=movies&movies_category=MOVIE&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/636a0f011d64eaaeae2496e8/inspect">Inspect</a>
ES: <a href="https://serpapi.com/playground?engine=google_play&gl=es&store=movies&movies_category=MOVIE&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/636a0f9dd737d73a33f18fdf/inspect">Inspect</a>
PL: <a href="https://serpapi.com/playground?engine=google_play&gl=pl&store=movies&movies_category=MOVIE&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/636a09da382427941b8808f8/inspect">Inspect</a>

**Comment by kagermanov27** [comment]
Just a clarification:
This issue is unrelated to changes in https://github.com/serpapi/SerpApi/pull/3308

**Comment by ilyazub** [comment]
These parameters didn't work because Google Play redirects from `https://play.google.com/store/movies/category/MOVIE?hl=en&gl=br` to `https://play.google.com/store/movies?hl=en&gl=br` but we didn't follow redirects.

![image](https://github.com/serpapi/public-roadmap/assets/282605/d1c9cc8a-99dc-47e6-ba01-64fab5dc1207)
(`curl -s -I https://play.google.com/store/movies/category/MOVIE?hl=en&gl=br`)

@ishiharaf Can you please add `follow_redirect` parameter to our Google Play Store Movies validator, double-check that `/search?engine=google_play_movies&gl=pl&hl=en&movies_category=MOVIE&no_cache=true` works, and submit a pull request?

**Comment by ishiharaf** [comment]
@marm123 Issue is solved and is no longer returning an error.

[Playground](https://serpapi.com/playground?engine=google_play_movies&gl=br&hl=en&movies_category=MOVIE&no_cache=true)
![image](https://github.com/serpapi/public-roadmap/assets/13112082/b109a09e-6d27-4f27-90e2-a96b872f66f7)

[Playground](https://serpapi.com/playground?engine=google_play_movies&gl=es&hl=en&movies_category=MOVIE&no_cache=true)
![image](https://github.com/serpapi/public-roadmap/assets/13112082/d9306f90-5ca8-4c30-bf7f-6b2906610ced)

[Playground](https://serpapi.com/playground?engine=google_play_movies&gl=pl&hl=en&movies_category=MOVIE&no_cache=true)
![image](https://github.com/serpapi/public-roadmap/assets/13112082/a0f840d2-77be-487e-8f6f-cef94edc3f9d)
