### ISSUE TITLE
[Google Reverse Image Search] API returns no results for all queries

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#491]
Looks like Google Reverse API is not working and returns no results for all queries.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/28161162/201274492-f4a34ba3-4c70-4dfa-b4a5-2f47ca2c7f41.png">

<a href="https://serpapi.com/playground?engine=google_reverse_image&image_url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fe%2Fe4%2FLatte_and_dark_coffee.jpg&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/636de531d5ecf4a0fab8f81d/inspect">Inspect</a>
<a href="https://serpapi.com/playground?engine=google_reverse_image&q=Apple&image_url=https%3A%2F%2Fwww.apple.com%2Fac%2Fstructured-data%2Fimages%2Fknowledge_graph_logo.png%3F202211040807&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/636de5bb2f542e4b0d2136ee/inspect">Inspect</a>
<a href="https://serpapi.com/playground?engine=google_reverse_image&q=Coffee&image_url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/636de5e7d5b1c5ed48dfb5ce/inspect">Inspect</a>

Seems unrelated to https://github.com/serpapi/public-roadmap/issues/369

**Comment by aciddjus** [comment]
Looks like they have fazed out `searchbyimage?` in URL and `image_url` parameter.

The new link is constructed with `tbs=sbi:encrypted_image_link`

e.g. https://www.google.com/search?tbs=sbi:AMhZZiv6E5S1bjiyMte7XT0fHh0YGFWOP1Hmniu0-oo_1VrYvGV8fxp-RArEfoBiZhETEvi5IIcP6YjUny262GORyWcWMnBCsMQaKCXAUiJbRdylQfmkDfbQny8WZeDYW5kRXRq-H_1I69OeZtkbI0BGjLJZiNXy3DMQ

1. Search Image by URL

<img width="605" alt="image" src="https://user-images.githubusercontent.com/6929257/201322909-bcd74426-5677-4fbb-8b67-0c2f4bef7e10.png">

2. Get Google Lens page

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/6929257/201323009-9a1ca2cc-8ec6-491c-a743-c5a39ee5ed5c.png">

3. Fallow link to Google Search

<img width="605" alt="image" src="https://user-images.githubusercontent.com/6929257/201323068-d5f65b76-18f9-45ab-9bd3-cc149f7e11bf.png">

**Comment by aciddjus** [comment]
This works for Google Lens: https://lens.google.com/uploadbyurl?url=https://i.imgur.com/HBrB8p0.png

**Comment by marm123** [comment]
It looks like a good band-aid solution, for now, @aciddjus. We can use the `tbs` parameter in regular Google Search API, and the results should be good enough. The only issue is that it requires a `q` parameter and manually searching for the `tbs` value via Google Lens. 

<a href="https://serpapi.com/playground?q=q&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbs=sbi%3AAMhZZisykRb-nsWkVUsR35jBbeWzx7BM-IPjxtQqBX5by1UwDkWkQzWQwbIyGShcGAQXUkUO2sXr8-rCVnCFNeCqBQm3XigVF1EOhRcFFcMTYYhmNJIGqeHLGnrXUiZM5rPcuGlx2Fhwcc6uzPV04dWVEHa-iAlppQ&device=desktop">Playground</a>

However, is there a way to approach it directly from Google Reverse Image Search API, or would the API need to be adjusted/redone?

**Comment by aciddjus** [comment]
> However, is there a way to approach it directly from Google Reverse Image Search API, or would the API need to be adjusted/redone?

Right now I don't see a way to do this. We need to refactor the API.

But before doing that we first need to find how to encrypt normal image URLs like: https://i.imgur.com/HBrB8p0.png to `tbs` required value like: `AMhZZiv6E5S1bjiyMte7XT0fHh0YGFWOP1Hmniu0-oo_1VrYvGV8fxp-RArEfoBiZhETEvi5IIcP6YjUny262GORyWcWMnBCsMQaKCXAUiJbRdylQfmkDfbQny8WZeDYW5kRXRq-H_1I69OeZtkbI0BGjLJZiNXy3DMQ`

So that we can make a search to: https://www.google.com/search?tbs=sbi:AMhZZiv6E5S1bjiyMte7XT0fHh0YGFWOP1Hmniu0-oo_1VrYvGV8fxp-RArEfoBiZhETEvi5IIcP6YjUny262GORyWcWMnBCsMQaKCXAUiJbRdylQfmkDfbQny8WZeDYW5kRXRq-H_1I69OeZtkbI0BGjLJZiNXy3DMQ

**Comment by aciddjus** [comment]
I also wonder if our Reverse Image Search API should move to support Google Lens instead of regular Search results. Since that seems to have become a default behavior. 🤔 

If we do that. We could probably extract the link to the regular search page and follow it to the results.

So, the new flow for our Reverse Image Search API could be:
1. Search with URL
2. Return Google Lens results, including the URL to the regular search page
3. Follow the URL to the regular search page and return results

**Comment by ilyazub** [comment]
Related to the previous @tanys123's [experiment with the image search with the file upload](https://github.com/serpapi/SerpApi/pull/2412#issuecomment-1093082354) and [Add Google Lens API](https://github.com/serpapi/SerpApi/issues/2356).

**Comment by dimitryzub** [comment]
Related: #494

**Comment by ritu1337** [comment]
The issue should be fixed now 🙂
