### ISSUE TITLE
[Google Search API] Some `related_questions` don't have `next_page_token`

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#507]
The expected behavior is to have `related_questions.next_page_token` at the playground when no `q` is applied. 

Users would understand that SerpApi provides such feature (pagination for related questions)

### `serpapi.com/playground`

When no `q` is applied, `next_page_token`, and `serpapi_link` is missing.

![image](https://user-images.githubusercontent.com/78694043/203524739-399d1ad3-ebb4-40f9-83ce-70ad64123b33.png)

### `serpapi.com/playground?q=<some_query>`

When `q` is applied, `next_page_token`, and `serpapi_link` is present.

![image](https://user-images.githubusercontent.com/78694043/203524827-9cc8cb6b-58b2-481d-ba7a-6c4eafd89faa.png)

**Comment by kagermanov27** [comment]
@dimitryzub Google search can't work without `q` parameter. Some results with `q=Coffee` is not returning `next_page_token`. I have looked into the issue and spotted that we have a scoping problem with css targets for questions. The issue happens when `data-lk` parameter cannot be extracted. I have checked the html and it is there. I will issue a fix for it right away.

**Comment by kagermanov27** [comment]
@dimitryzub Nevertheless, a great catch. I like subtle catches like this. Requires true attention.
