### ISSUE TITLE
[Google Maps API] Results not Related to GPS Coordinates

### ISSUE THREAD

**Issue by wofguy** [serpapi/public-roadmap#552]
Problem: When using the Google Maps API, sometimes the results are not related to the entered GPS coordinates. However, when using the Google Maps URL returned, it gives the correct results so the issue is tied to the API.

Example: @33.5000443,-112.0872057,14z is Phoenix, AZ. Results have been for Hallandale Beach, FL and Oakdale, NY.

[Playground](https://serpapi.com/playground?engine=google_maps&q=self+storage+near+me&ll=%4033.5000443%2C-112.0872057%2C14z&hl=en&type=search)
[Google Maps URL](https://www.google.com/maps/search/self+storage+near+me/@33.5000443,-112.0872057,14z?hl=en)

![image](https://user-images.githubusercontent.com/63465495/210643051-cb0b7e64-755c-418f-8216-4e1a243d69a5.png)

Attached file is a list of recent searches that had irrelevant results along with similar searches that had valid results.
[Phoenix - search ids.xlsx](https://github.com/serpapi/public-roadmap/files/10347483/Phoenix.-.search.ids.xlsx)

**Comment by dimitryzub** [comment]
@wofguy Thank you for opening this issue 👍

What do you think about adding an address next to the search query, meaning:

-  `<address>, <query>` which translates to..
- `Hallandale Beach, FL and Oakdale, NY, self storage near me`  ([result on Google Maps](https://www.google.com/maps/search/Hallandale+Beach,+FL+and+Oakdale,+NY,self+storage+near+me/@33.5000443,-112.0872057,14z?hl=en), red place markers disappeared)

I get the following result (before, in the playground, without an explicit address next to query map doesn't show up as you showed in your screenshot):

|Google Maps|Playground|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/210712857-a3f10e0a-2a55-4ecb-8480-1ec2b8a6f51b.png)|![image](https://user-images.githubusercontent.com/78694043/210712175-221da7d7-80e6-4f54-8224-58e39b791db1.png)|

## Making search more explicit

What do you think about rephrasing the search query to a more explicit one? (making it non-[ambigious](https://developers.google.com/maps/documentation/places/web-service/search-text) which Google can translate to Geo coordinates)

`self storage near me` -> `self-storage in Hallandale Beach, FL and Oakdale, NY`

Or even better: `Hallandale Beach, FL, self-storage` and another query `Oakdale NY, USA, self-storage`. I'm not sure if Google can show the correct places from two different places (Florida and New York) at the same time. 

In the second query, I've added `USA` to make the search more explicit, otherwise, results may be not as expected.

### If the search is split into two queries

By two queries I mean to search for results from Florida and New York _separately_.

#### Hallandale Beach, FL, self-storage  

[Google Maps URL](https://www.google.com/maps/search/Hallandale+Beach,+FL,+self-storage++/@25.975949,-80.1967614,13z/data=!3m1!4b1?hl=en) | [Playground](https://serpapi.com/playground?engine=google_maps&q=Hallandale+Beach%2C+FL%2C+self-storage&ll=%4025.975949%2C-80.1967614%2C13z&hl=en&type=search)

|Google Maps|Playground|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/210714969-1a0b2b0d-aeb4-405f-9737-24c9436428fb.png)|![image](https://user-images.githubusercontent.com/78694043/210715000-7487867f-1c4c-43eb-a854-8a80cb4639e6.png)|

![image](https://user-images.githubusercontent.com/78694043/210714947-f6867300-1bbc-476a-8fdb-df1eedeeeee7.png)
____

#### Oakdale NY, USA, self-storage

[Google URL](https://www.google.com/maps/search/Oakdale+NY,+USA,+self+storage++/@40.8238424,-73.2033435,10.35z/data=!4m2!2m1!6e2?hl=en) | [Playground](https://serpapi.com/playground?engine=google_maps&q=Oakdale+NY%2C+USA%2C+self+storage++&ll=%4040.8238424%2C-73.2033435%2C10.35z&hl=en&type=search)

|Google Maps|Playground|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/210715620-decd7c9c-e6a7-43e8-a986-aa66ea56f944.png)|![image](https://user-images.githubusercontent.com/78694043/210715672-5d07f945-7a5b-42c4-b8b5-dddca9af51cb.png)|:

![image](https://user-images.githubusercontent.com/78694043/210715925-98e22c90-1bd0-42ad-8061-e24a11649b8c.png)

____

Ref:
- Making search more explicit: https://developers.google.com/maps/documentation/places/web-service/search-text
- Geocoding Addresses Best Practices: https://developers.google.com/maps/documentation/geocoding/best-practices

Let me know if you need additional help, or if it doesn't make any sense 🙂

______

P.S. - would it be beneficial to you if we have an option to just extract all possible places from a given boundary? For example, from all `Oakdale, New York`. 

![google-search-serpapi](https://user-images.githubusercontent.com/78694043/210717138-794e90e3-2f4b-4b56-9ac0-1d55342d6515.gif)

**Area with boundaries**: city Tivoli in Italy.
**Keyword**: supermarkets.
**End result**: extract supermarkets from whole city Tivoli.

Ref: 
- https://github.com/serpapi/public-roadmap/issues/186

**Comment by wofguy** [comment]
> @wofguy Thank you for opening this issue 👍
> 
> > @33.5000443,-112.0872057,14z is Phoenix, AZ. Results have been for Hallandale Beach, FL and Oakdale, NY.
> 
> The results differ seems to be because of Geo coordinates you passed from `Phoenix, AZ`, instead of coordinates from either `Hallandale Beach, FL` or `Oakdale, NY`.
> 

@dimitryzub The issue is that I passed Phoenix, AZ coordinates, **expecting Phoenix, AZ results**, but instead got results for Hallandale Beach, FL and Oakdale, NY. The results are in completely different states from the coordinates I entered into the API.

**Comment by ritu1337** [comment]
@wofguy try dropping the `near me` phrase from the keyword, so instead of `self storage near me` search for `self storage`.

There's a mention about using `near me` in your keyword in the [Google Maps API documentation](https://serpapi.com/google-maps-api):

> Some results may be inaccurate for the provided geographic location. Particularly `near me` keyword in query will show results not for provided coordinates.

**Comment by wofguy** [comment]
@ritu1337 Thank you for pointing out the documentation's mention of that. I'll use Google Search API instead.
