### ISSUE TITLE
[Google Maps API] "Permanently Closed" Warning not Parsed and Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#564]
"Permanently Closed" Warning in search results page is not parsed and returned in Google Maps API response.

![maps_permanently_closed_png](https://user-images.githubusercontent.com/64849049/211850753-40fe2892-8fab-4f04-9cee-a5a28ad7e861.png)

[The Playground](https://serpapi.com/playground?engine=google_maps&q=car+wash+801+S+Beard+St%2C+Shawnee%2C+OK+74801&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search) | [The Inspect](https://serpapi.com/searches/63becd3d5119a62702d4fbf1/inspect) | [Google Maps](https://www.google.com/maps/search/car+wash+801+S+Beard+St,+Shawnee,+OK+74801/@40.7455096,-74.0083012,14z?hl=en)

**Comment by aliayar** [comment]
The status could be either of below:

- CLOSED_PERMANENTLY
- CLOSED_TEMPORARILY
- OPERATIONAL

**Comment by aciddjus** [comment]
In this case, we extract `Permanently closed` but not `Temporarily closed`:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/6929257/212076254-df353997-f5f6-4159-b572-51c55733c587.png">

It seems that when `operating_hours` or `hours` are missing from the response, so is the `open_state`.

-----------------

I only found traces of it in one of Google Maps Javascript files:

![image](https://user-images.githubusercontent.com/6929257/212081334-7a3211e1-1f09-41a3-a744-32f76e69b9c1.png)

But that's not super helpful since there is no obvious indication in the response if a place is permanently or temporarily closed.

-----------------

In the example search from the issue, there is a `CLOSED` state that we could extract:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/6929257/212082787-e3bfc118-90b9-4e72-9260-ce99fad694e0.png">

But for the next search, at the same position in Google Maps, the response has something unrelated:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/6929257/212083205-b4d3b474-3e47-4b85-bebc-fabf1a334a00.png">

-------------------

**Comment by schaferyan** [comment]
Another customer reported this issue. In this case it is `temporarily_closed` we are not parsing.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000048758?view=List) | [Inspector](https://serpapi.com/searches/64f8c7c6af5af1492a7eb2f0/inspect)

**Comment by zyc9012** [comment]
Sometimes it does have "Temporarily closed" info

![image](https://github.com/serpapi/public-roadmap/assets/3034310/2e9cf399-c955-4279-82d7-a7592181224d)

[Inspect](https://serpapi.com/searches/64f933071baebbab279ceeb1/inspect)
[Playground](https://serpapi.com/playground?engine=google_maps&q=temporarily+closed&ll=%4040.7688618%2C-73.736538%2C11z&hl=en&type=search)
[Google Maps Search](https://www.google.com/maps/search/temporarily+closed/@40.7688618,-73.736538,11z?hl=en&entry=ttu)
