### ISSUE TITLE
[Yahoo Search API] Missing to extract `sitelinks`

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#642]
![screenshot](https://user-images.githubusercontent.com/6929257/218438208-a1492997-c693-4428-a8a1-36a9e3df818f.png)

[Playground](https://serpapi.com/playground?engine=yahoo&p=xbox&device=mobile&no_cache=true)
[Inpsect](https://serpapi.com/searches/63ea3629fe41d01d600117ad/inspect)

**Comment by kagermanov27** [comment]
@zyc9012 The inspect link and the image belong to `Yahoo Search API`, and the issue is mentioned in a PR about `Yahoo Search API` as well. Playground Link and Title are about `Bing Search API`. The Playground link is showing the correct results. Have you come across a problematic search in `Bing Search API` really or was it just a naming confusion?

**Comment by zyc9012** [comment]
@kagermanov27 Oh! How careless of me. Thanks for checking, my mind was messed up. I've corrected the naming.
