### ISSUE TITLE
[Google Search API] Location Parameter Ignored When `gl` is not Provided

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#738]
A user reported that they are getting results for the wrong location when `gl` is not provided. For example, the location "Atlanta, GA, United States" is returning results in Indonesian. I was unable to replicate this in the Playground.

<img width="1011" alt="Screenshot 2023-03-23 at 10 12 18 AM" src="https://user-images.githubusercontent.com/30915304/227283778-3b118d83-de60-46ef-9cfc-ecfac4b0eb00.png">

[JSON](https://serpapi.com/searches/d4efd29fb9d34451/641c754711c88142b9ccf643.json) | [Search Inspector](https://serpapi.com/searches/641c754711c88142b9ccf643/inspect)

**Comment by ilyazub** [comment]
If results are for Indonesia, it may be related to proxies.

**Comment by marm123** [comment]
I'm unsure if this is solely connected to proxies or if our `location` parameter is ignored. If we don't set the `gl` parameter at all, the `location` parameter seems to have no effect:

[Gdansk, Pomeranian Voivodeship, Poland
](https://serpapi.com/playground?q=Football&location=Gdansk%2C+Pomeranian+Voivodeship%2C+Poland&no_cache=true)<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28161162/227881284-ed45d570-0d36-422f-899b-77972e6a2a45.png">

[State of Sao Paulo, Brazil
](https://serpapi.com/playground?q=Football&location=State+of+Sao+Paulo%2C+Brazil&no_cache=true)<img width="1436" alt="image" src="https://user-images.githubusercontent.com/28161162/227881583-90ba7d8d-d1b5-4f71-b9f9-0cb288a4170b.png">

[Tel Aviv District, Israel
](https://serpapi.com/playground?q=Football&location=Tel+Aviv+District%2C+Israel&no_cache=true)<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28161162/227881874-765ec13b-0cd5-4c0f-b57e-32c1d80d8c91.png">

And if we set the `gl` parameter to force the results from a specific country, we can't get results in English for non-English locations, because the `hl` parameter is not working at all. Related: https://github.com/serpapi/public-roadmap/issues/643

**Comment by schaferyan** [comment]
Closing this, as it no longer seems to be a problem. Feel free to re-open if that's not the case.
