### ISSUE TITLE
【registration failed】Unable to register, registration failed

### ISSUE THREAD

**Issue by wumyuan** [serpapi/public-roadmap#780]
We couldn't create your account due to activity on your network. Please contact our support.

![image](https://user-images.githubusercontent.com/19402458/230893301-491403f1-9cea-4e20-9fa9-92a68fce7bad.png)

**Comment by hilmanski** [comment]
We apologize for the very long delay in getting back to you. 

_For future reference or in case other people are facing this issue:_
This is usually due to using a VPN. Feel free to try to register without using a VPN. Or vice versa, try to use a VPN if your default network doesn't allow you to register.
