### ISSUE TITLE
[Google Shopping API] Some Products Have a Faulty ID

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#846]
I'm not sure whether this is on our side or Google's, but some products found in Google Shopping searches have a `product_id` that returns empty results when searched with the Product API.

<img width="1464" alt="Screenshot 2023-05-10 at 4 13 16 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/60466fad-25a0-43ef-b119-415fcb5448db">
<img width="1453" alt="Screenshot 2023-05-10 at 4 14 09 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/9a81a99b-0141-44a8-9334-2f0a01e50a2f">

[Playground (Shopping)](https://serpapi.com/playground?engine=google_shopping&q=Best-Vegan-Muffin-Morango-e-Banana-500g&gl=br&hl=pt) | [Playground(Product) ](https://serpapi.com/playground?engine=google_product&product_id=7746179670829688215&gl=us&hl=en)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040994?view=List)

**Comment by marm123** [comment]
Related: https://github.com/serpapi/public-roadmap/issues/454

**Comment by aliayar** [comment]
I thought that `product_id` search does not return any results because of the hl and gl difference between search (br, pt) and product (us, en). But that's not the case.

https://serpapi.com/playground?engine=google_product&product_id=7746179670829688215&gl=br&hl=pt

Adding location also does not help.

https://serpapi.com/playground?engine=google_product&product_id=7746179670829688215&location=Guarulhos%2C+State+of+Sao+Paulo%2C+Brazil&google_domain=google.com.br&gl=br&hl=pt

**Comment by ghostmanbobby** [comment]
***@***.***

**Comment by schaferyan** [comment]
Another user reported this

[Search Inspector (Shopping)](https://serpapi.com/searches/64da53bec99903348bbd6d9a/inspect) | [Search Inspector (Product)](https://serpapi.com/searches/64da5badaf5af13f48465aa3/inspect) | [Playground](https://serpapi.com/playground?engine=google_product&product_id=15350551267474194948&gl=us&hl=en) |[ Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000046241?view=List)
