### ISSUE TITLE
[New Integration] Add SerpApi plugin to ChatGPT

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#904]
GPT-4 plugins are officially available. SerpApi plugin for ChatGPT may be useful to fetch data from other search engines in addition to Bing (an official Web Browsing plugin for the GPT-4 model). Let's check if someone is interested before implementing. 

ChatGPT plugins quickstart: https://github.com/openai/plugins-quickstart
External service authentication example: https://github.com/openai/chatgpt-retrieval-plugin/blob/main/examples/authentication-methods/service-http/ai-plugin.json

**Comment by hilmanski** [comment]
People can create a "custom GPT" that utilizes SerpApi: https://serpapi.com/blog/how-to-connect-chatgpt-to-the-internet/

**Comment by hartator** [comment]
@hilmanski Should we close this then or this is still relevant?

**Comment by hilmanski** [comment]
By the latest commit, it seems that "Plugin" has been replaced with "Custom GPT." 

Ref: https://github.com/openai/plugins-quickstart/commit/0763ac2bc52f45f3c09f71f6c1a7890b75277dc5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4

I've shared the tutorial on how to make it via [blog](https://serpapi.com/blog/how-to-connect-chatgpt-to-the-internet/) and [YouTube Video](https://www.youtube.com/watch?v=6-4BJOW_b94).  We teach how to build custom GPT in this tutorial, but it's private since we require an API key for that.

It's also less relevant since OpenAI announced [search capabilities for ChatGPT](https://openai.com/index/introducing-chatgpt-search/).

We can still **build** a specific custom GPT, for example, a "shopping assistant" that utilizes our Google Shopping API. It can be part of marketing where the user will use "free credits" for their searches (no authentication).

I'll close this thread for now. Feel free if anyone wants to build these custom GPTs.
