### ISSUE TITLE
[Google Search API Answer Box] New Answer Box to be Scraped

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#961]
Google shows the new design of the answer box which shows 3 answers in small boxes. Currently, we don't scrape any of those answers.

![new_answer_box](https://github.com/serpapi/public-roadmap/assets/64849049/fd07368f-9d09-46e9-bfd0-6fc97cc26c24)

I couldn't reproduce this result as Google still shows old design. But this new design can be found in Inspect Link.

[Playground Link ](https://serpapi.com/playground?q=ecommerce+conversion+rate&gl=us&hl=en&num=100)| [Inspect Link](https://serpapi.com/searches/649b9021654a8c417d354af3/inspect) | [Google](https://www.google.com/search?q=ecommerce+conversaion+rate) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043657?view=List)

**Comment by tatianatanizaki** [comment]
Hi there! Here is another case:

![Screenshot 2023-06-30 at 2 05 58 PM](https://github.com/serpapi/public-roadmap/assets/39380403/177a6a5e-9733-42e5-ac62-c1982c99b16e)

**Comment by tatianatanizaki** [comment]
And another 😀 
<img width="1196" alt="Screenshot 2023-07-07 at 10 38 46 AM" src="https://github.com/serpapi/public-roadmap/assets/39380403/d12b9dcf-062d-4237-a3ff-e89362f889c8">

**Comment by tatianatanizaki** [comment]
Google continues to test 2-3 sources on this featured snippet. We can't get an accurate reading for this keyword, since the FS positions are not counted.

Here is the search id to reproduce this behaviour:
**id:** 64b639371071f412bdcbe5cd

<img width="653" alt="Screenshot 2023-07-18 at 9 38 20 AM" src="https://github.com/serpapi/public-roadmap/assets/39380403/7a530ab6-0b2d-4424-b796-b6f140d90843">
